### ISSUE TITLE
SIGSEGV in redis branch

### ISSUE THREAD

**Issue by mezzatto** [twitter/twemproxy#10]
While running a update process of my Redis instance, a Segmentation Fault occurred. The process was sending a lot of HMSETs, HDELs and PERSIST the Redis.

The SIGSEGV happens every time I run my update process.

My update process uses HiRedis opening a single TCP connection to the server em sending commands with the async API.

Config:

alpha:
  listen: 127.0.0.1:22121
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
- 127.0.0.1:63700:1

Compiled with debug logs, the output was the following:

[Mon Aug 13 17:33:29 2012] nc_parse.c:1052 parsed req 121 res 0 type 37 state 0 rpos 31 of 316
[Mon Aug 13 17:33:29 2012] nc_parse.c:1053 
00000000  2a 32 0d 0a 24 37 0d 0a  50 45 52 53 49 53 54 0d   |_2..$7..PERSIST.|
00000010  0a 24 38 0d 0a 6f 4d ff  3c 05 bd fa 0f 0d 0a 2a   |.$8..oM.<......_|
00000020  38 0d 0a 24 35 0d 0a 48  4d 53 45 54 0d 0a 24 38   |8..$5..HMSET..$8|
00000030  0d 0a 6f af 00 3d 05 48  be 0d 0d 0a 24 31 0d 0a   |..o..=.H....$1..|
00000040  64 0d 0a 24 31 30 30 0d  0a 54 6f 63 61 20 44 56   |d..$100..Toca DV|
00000050  44 20 6e 6f 20 66 6f 72  6d 61 74 6f 20 64 65 20   |D no formato de |
00000060  63 61 72 72 6f 2c 20 63  6f 6d 20 65 6e 74 72 61   |carro, com entra|
00000070  64 61 20 55 53 42 20 65  20 63 6f 6e 74 72 6f 6c   |da USB e control|
00000080  65 20 72 65 6d 6f 74 6f  2c 20 63 6f 6d 70 61 74   |e remoto, compat|
00000090  ed 76 65 6c 20 63 6f 6d  20 44 56 44 20 2f 20 56   |.vel com DVD / V|
000000a0  43 44 20 2f 20 43 44 20  2f 20 4d 50 33 0d 0a 24   |CD / CD / MP3..$|
000000b0  31 0d 0a 69 0d 0a 24 36  30 0d 0a 68 74 74 70 3a   |1..i..$60..http:|
000000c0  2f 2f 74 68 75 6d 62 73  2e 62 75 73 63 61 70 65   |//thumbs.buscape|
000000d0  2e 63 6f 6d 2e 62 72 2f  54 31 30 30 78 31 30 30   |.com.br/T100x100|
000000e0  2f 5f 5f 32 2e 39 30 30  36 38 30 2d 35 33 64 30   |/__2.900680-53d0|
000000f0  30 61 66 2e 6a 70 67 0d  0a 24 31 0d 0a 70 0d 0a   |0af.jpg..$1..p..|
00000100  24 35 36 0d 0a 68 74 74  70 3a 2f 2f 77 77 77 2e   |$56..http://www.|
00000110  73 68 6f 70 69 6e 74 65  72 6e 61 63 69 6f 6e 61   |shopinternaciona|
00000120  6c 2e 63 6f 6d 2e 62 72  2f 3f 70 61 67 65 3d 64   |l.com.br/?page=d|
00000130  65 74 61 6c 68 65 26 69  64 3d 32 38               |etalhe&id=28|
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10060) [0x7f427cb4b060]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [1] /lib/x86_64-linux-gnu/libc.so.6(_IO_vfprintf+0x2775) [0x7f427c55fc65]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [2] /lib/x86_64-linux-gnu/libc.so.6(__vsnprintf_chk+0xb0) [0x7f427c60ea90]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [3] ./src/nutcracker(_vscnprintf+0x1b) [0x417cdb]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [4] ./src/nutcracker(_log+0x151) [0x416c31]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [5] ./src/nutcracker(parse_request+0xb65) [0x40fa85]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [6] ./src/nutcracker(msg_recv+0xb9) [0x40cf99]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [7] ./src/nutcracker(core_loop+0x1c9) [0x4096a9]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [8] ./src/nutcracker(main+0x528) [0x408b68]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f427c53730d]
[Mon Aug 13 17:33:29 2012] nc_util.c:291 [10] ./src/nutcracker() [0x408f59]
[Mon Aug 13 17:33:29 2012] nc_signal.c:122 signal 11 (SIGSEGV) received, core dumping
Segmentation fault

**Comment by w3hacker** [comment]
@mezzatto lastest hiredis can't connect to twemproxy. Do you know why? Thanks.

**Comment by mezzatto** [comment]
@w3hacker, I do not know. Sorry.

Have you checker if twemproxy is bound to some specific interface ("listen" option)?
