### ISSUE TITLE
Twemproxy for Load Balancing

### ISSUE THREAD

**Issue by hrishimantri** [twitter/twemproxy#110]
Hi,
We are exploring options to configure twemproxy so that it can load balance the GET requests across multiple REDIS slaves (note : no sharding) maybe in a Round Robin fashion. What is the best way of doing this using twemproxy ? We are also exploring to do this at the Jedis client side.

**Comment by BinWu1989** [comment]
@hrishimantri @manjuraj , could you kindly helps to explain how the twemproxy load balancing works ?which algorithm it takes to forward the request when distribution set to random?

**Comment by BinWu1989** [comment]
@manjuraj by the way , could you kindly advise how can we known which instance the request was forward to ?
