### ISSUE TITLE
Performance degradation with large multi gets

### ISSUE THREAD

**Issue by nikhilgarg28** [twitter/twemproxy#111]
It appears that multi-gets with large number of keys are substantially slow with nutcracker. 

In this example, we talk to nutcracker listening on shady2:11222 . Its pool consists of a single memcached server listening on shady2:22122. We also directly talk to another mc server which is listening on shady2:11211. 

``` python
In [1]: def get_keys(num):
   ...:     s = 'a' * 100
   ...:     return [s + str(i) for i in xrange(num)]
   ...: 

In [2]: keys10 = get_keys(10)

In [3]: keys100 = get_keys(100)

In [4]: keys1000 = get_keys(1000)

In [5]: keys10000 = get_keys(10000)

In [6]: import cmemcached

In [7]: mc = cmemcached.Client(['shady2:11222'])

In [8]: %timeit mc.get_multi(keys10)
1000 loops, best of 3: 651 us per loop

In [9]: %timeit mc.get_multi(keys100)
100 loops, best of 3: 2.5 ms per loop

In [10]: %timeit mc.get_multi(keys1000)
10 loops, best of 3: 64.8 ms per loop

In [11]: %timeit mc.get_multi(keys10000)
1 loops, best of 3: 181 ms per loop

In [12]: non_nc_mc = cmemcached.Client(['shady2:11211'])

In [13]: %timeit non_nc_mc.get_multi(keys10)
1000 loops, best of 3: 463 us per loop

In [14]: %timeit non_nc_mc.get_multi(keys100)
1000 loops, best of 3: 782 us per loop

In [15]: %timeit non_nc_mc.get_multi(keys1000)
100 loops, best of 3: 2.26 ms per loop

In [16]: %timeit non_nc_mc.get_multi(keys10000)
100 loops, best of 3: 14.2 ms per loop

In [17]: 
```

Is it usual? Is it possible to configure nutcracker to improve performance? ( I am already running nutcracker with 64K mbuf size and  upto100 server_connections)

**Comment by rockysoar** [comment]
I strace my apache process:
connect(60, {sa_family=AF_FILE, path="/var/run/nutcracker/nutcracker_goshop.redis-s0100.51fanli.it_6605.sock"}, 72) = 0 <0.000030>
fcntl(60, F_SETFL, O_RDWR) = 0 <0.000050>
setsockopt(60, SOL_TCP, TCP_NODELAY, [1], 4) = -1 EOPNOTSUPP (Operation not supported) <0.000010>
poll([{fd=60, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout) <0.000010>
sendto(60, "*2\r\n$7\r\nHGETALL\r\n$41\r\ngoshop:secondtaoke:item:time:521832288205\r\n", 65, MSG_DONTWAIT, NULL, 0) = 65 <0.000012>
poll([{fd=60, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout) <0.000043>
**poll([{fd=60, events=POLLIN|POLLERR|POLLHUP}], 1, 120000) = 1 ([{fd=60, revents=POLLIN}]) <1.877846>**
recvfrom(60, "*0\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 4 <0.000022>

**Why poll(POLLIN) after sendto consume amazing 1.877846s?**  

My configuration:
--mbuf-size is 4096000
listen: /var/run/nutcracker/nutcracker_redis.51fanli.it_6381.sock 0777
    hash: md5
    distribution: modula
    auto_eject_hosts: false
    server_connections: 1
    preconnect: true
    backlog: 4096
    timeout: 500
    redis: true
    servers:
        - redis.51fanli.it:6381:1

$ nc 10.0.8.210 22222|python -m json.tool|grep curr_connections
    "curr_connections": 1251,
