### ISSUE TITLE
Method to know which server was selected for a key

### ISSUE THREAD

**Issue by jbmclaughlin** [twitter/twemproxy#118]
Hey all-

First off, excellent job on Twemproxy.  Our company is looking for an easy-to-use, consistent hashing solution for Redis, and this tool meets all our needs.

Question: Is there a way to know which server was selected for a particular key?

The reason I'm asking is because we might want to map several virtual servers to the same redis instance to establish our initial hash-ring and simultaneously reduce costs.  Knowing which server was initially selected will help us with data migration in the future.

Thanks again for releasing this to the community...it's a big help for start-ups looking for an out-of-the-box solution before redis cluster.

Cheers,
J

**Comment by TysonAndre** [comment]
`EVAL "return redis.call('info', 'server');" 1 keytolookup` can be used to fetch information about the server, potentially including the port or the config file name (if started with a config file). Redis will send `EVAL` commands to a server based on the first key in an EVAL command

(`keytolookup` is the literal name to lookup)

It should contain something like `config_file:/etc/redis/db009.conf`, which would be useful if the config name is globally unique and doesn't change

**Comment by TysonAndre** [comment]
I'm assuming https://github.com/twitter/twemproxy/issues/118#issuecomment-830876378 answers the original question about redis.

I'm not sure of the plans for the key_to_server branch, but from it having never been merged I assume it wasn't planned?
