### ISSUE TITLE
Expire DNS caching

### ISSUE THREAD

**Issue by yashh** [twitter/twemproxy#13]
So we had a pool with a bunch of memcaches in it. One of the memcache server became unresponsive and we had to swap it with a new server. We brought the new machine with the same hostname as the dead one, expecting nutcracker to try the new server. But nutcracker upon startup performs a DNS lookup and uses ip address to connect to the hosts. In this case we had to restart nutcrackers all over place. Can we use hostnames ? But that might not be ideal. So a cache of hostname to ip address with some 15 mts expiration would be ideal.

**Comment by manjuraj** [comment]
@yashh issue 13 is finally getting resolved :) Details here: https://github.com/twitter/twemproxy/issues/355#issuecomment-113575050 and this patch fixed it: https://github.com/twitter/twemproxy/commit/fd34c29bb69861b37eea786bd84a7e437ab8bb7c
