### ISSUE TITLE
Challenges in running multiple instances of twemproxy?

### ISSUE THREAD

**Issue by devcamcar** [twitter/twemproxy#17]
Hello, I have a question about running multiple instances of twemproxy, and specifically what happens when adding/removing memcached backends.

For instance, if I have two instances of twemproxy running with exactly the same configuration, and then need to add a new backend node, what risks are there in terms of having to synchronize the process restarts, etc?

Consider the following scenario:

twemproxy A refers to memcached servers 1, 2 and 3

twemproxy B refers to memcached servers 1, 2 and 3

At this point everything is in synch and working well.

What happens in this case if you:

Add server 4 to twemproxy A and restart the process

Wait 5 number of minutes

Add server 4 to twemproxy B and restart the process

In the 5 minutes between, are the two instances of twemproxy now using different ring/hashing algorithms?  

Thanks in advance - just trying to get a feel for the best practices around using multiple instances of twemproxy.

**Comment by prokashyap** [comment]
HI @manjuraj ,
I have two twemproxy running in two different machine and both the twemproxy is connected to the same two redis which are running in another machine.
To avoid confusion Twemproxy 1 is running in Machine A, Twemproxy 2 is running Machine B and the two redis, Redis 1 and Redis 2 is running in machine C.
These 2 twemproxy were installed just to push the data in Redis.
Later, I installed 1 more Twemproxy 3 in Machine C where the Redis is running for reading the values from Redis, but it is behaving abnormally, I mean it is returning null value for that data also which is present in Redis.

If possible can you please give me some advice or abnormal behaviour by twemproxy while running in production. It will be really helpuful.
Thanks
