### ISSUE TITLE
When auto eject is set to true and twemproxy reconnects it needs to do hostname resolution

### ISSUE THREAD

**Issue by venkatkalluru** [twitter/twemproxy#170]
Problem: Twemproxy does not do a host name resolution when it reconnects to a server. The reason for this is, it does cache the IP address which is resolved at start up time. 

We have a cluster setup with sharding enabled. So we have a virtual IP  configured in the twemproxy configuration, where it maps to two servers. So when one goes down, we would like to connect to the other one and for this to happen, when twemproxy reconnects it needs to resolve the hostname.

**Comment by tom-dalton-fanduel** [comment]
It looks like this never got finished. I can see a PR https://github.com/twitter/twemproxy/pull/177 that looks like it's abandoned. This feature would be quite useful for us - is there any appetite for resurrecting it?

**Comment by manjuraj** [comment]
Fixed with https://github.com/twitter/twemproxy/commit/fd34c29bb69861b37eea786bd84a7e437ab8bb7c

Detail here: https://github.com/twitter/twemproxy/issues/355#issuecomment-113575050
