### ISSUE TITLE
Connection timed out to AWS elasticache

### ISSUE THREAD

**Issue by xaratt** [twitter/twemproxy#18]
Found a strange bug when was trying to run twemproxy with cluster of elasticache (Amazon cloud memcached) servers. Amazon use CNAMEs as entry points for elasticache servers and twemproxy could connect to the backend memcached on start, but couldn't send any request to them. If I use "direct" hostnames for the backend servers, all requests are ok.

<pre>
user@localhost:~$ telnet my.proxy.server 11311
Trying xx.xx.xx.xx...
Connected to xx.xx.xx.xx.
Escape character is '^]'.
get foo
SERVER_ERROR Connection timed out
^]
</pre>

twemproxy config:

<pre>
staging-cache:
  listen: 0.0.0.0:11311
  hash: fnv1a_64
  distribution: ketama
  timeout: 10000
  backlog: 1024
  preconnect: true
  auto_eject_hosts: true
  server_retry_timeout: 30000
  server_failure_limit: 3
  servers:
   - myserver.0001.use1.cache.amazonaws.com:11211:1
   - myserver.0002.use1.cache.amazonaws.com:11211:1
   - myserver.0003.use1.cache.amazonaws.com:11211:1
   - myserver.0004.use1.cache.amazonaws.com:11211:1
</pre>

twemproxy was running as

<pre>
user@my.proxy.server:~$ nutcracker -c /etc/nutcracker.yml -v 11
</pre>

Here is part of twemproxy log: http://pastebin.com/DTE8gAva

When I modified servers section:

<pre>
  servers:
   - ec2-xx-xx-xx-xx.compute-1.amazonaws.com:11211:1
   - ec2-xx-xx-xx-xx.compute-1.amazonaws.com:11211:1
   - ec2-xx-xx-xx-xx.compute-1.amazonaws.com:11211:1
   - ec2-xx-xx-xx-xx.compute-1.amazonaws.com:11211:1
</pre>

I received response:

<pre>
user@localhost:~$ telnet my.proxy.server 11311
Trying xx.xx.xx.xx...
Connected to xx.xx.xx.xx.
Escape character is '^]'.
get foo
END
^]
</pre>

And, of course, *.cache.amazonaws.com could be resolved from instance where twemproxy is running:

<pre>
user@my.proxy.server:~$ host myserver.0002.use1.cache.amazonaws.com
myserver.0002.use1.cache.amazonaws.com is an alias for ec2-xx-xx-xx-xx.compute-1.amazonaws.com.
ec2-xx-xx-xx-xx.compute-1.amazonaws.com has address xx-xx-xx-xx
</pre>

P.S. Oct 26 code snapshot was used; Ubuntu 12.04.1 x86_64

**Comment by tom-dalton-fanduel** [comment]
Xaratt did you ever get to the bottom of this?

We recently saw a similar-sounding issue (twemproxy appears to connect but then commands result in "ERR Connection timed out" with an Elasticache Redis write endpoint. It was intermittent but I will attempt to gather more info if it happens again.

**Comment by xaratt** [comment]
@tom-dalton-fanduel, sorry for delay in responding, but we didn't found source or solution for this problem. We only added CNAMEs for each of our memcache nodes.

**Comment by tom-dalton-fanduel** [comment]
No problem - it looks like this was unrelated to an issue we were looking at!

**Comment by digitalprecision** [comment]
Confused. Isn't EC Cluster endpoint a proxy, like twemproxy? Why deal with two proxies, rather set your app to connect directly to the EC Cluster endpoint.

**Comment by tom-dalton-fanduel** [comment]
Twemproxy is more than just a proxy, it provides transparent sharding too. In my case (and I'm guessing @xaratt 's too?) twemproxy is used to shard across multiple EC [write] endpoints.

**Comment by smehtaCAS** [comment]
@tom-dalton-fanduel I am having similar issue as you. Did you find out what the problem was. Thanks

**Comment by tom-dalton-fanduel** [comment]
I'm afraid I don't even remember the context for my comment, let alone if we ever solved it. We've since moved away from Twemproxy.

**Comment by digitalprecision** [comment]
Same... we ended up using aws elasticache instead.

**Comment by smehtaCAS** [comment]
We use AWS elasticache as well but intermittently we get "ERR Connection timed out" Could not see anything in the logs.

**Comment by digitalprecision** [comment]
Did u try installing the aws specific module? It’s supposed to support
ejections

**Comment by smehtaCAS** [comment]
I have not. Can you point me to it. Thanks!

**Comment by digitalprecision** [comment]
I can't remember specifically, it's been a few years, but a google search
should find something. Or start here:
https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/Appendix.PHPAutoDiscoverySetup.html

**Comment by TysonAndre** [comment]
I wonder if https://github.com/twitter/twemproxy/pull/567 was related - until that's merged, ketama_max_hostlen is 86. (if it works for short names but not long names)

But I don't see how that'd possibly be the issue, it'd just hash requests to the wrong host. (snprintf still appends null characters)

(looking at this issue while looking into whether timeouts are more likely with elasticache in general - doesn't seem like it)

**Comment by TysonAndre** [comment]
Leaving a note on this to refer back to later in case anyone else has issues with elasticache memcached - the issue I'm looking into is unrelated

https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/ParameterGroups.Memcached.html suggests there's no timeout, so I'm confused

- It could be a bug parsing requests or responses in an older version
- It could be intermittent issues with connectivity from a datacenter or application to elasticache 

Elasticache itself doesn't have an idle timeout according to recent documentation for 1.4, not sure if old versions were different

idle_timeout | Default: 0 (disabled)Type: integerModifiable: YesChanges Take Effect: At Launch | The minimum number of seconds a client will be allowed to idle before being asked to close. Range of values: 0 to 86400.
-- | -- | --

--------

I think https://github.com/twitter/twemproxy/pull/324/files#diff-01600ca8f8e542768f785de1842f38b3aeeb315531c63b9d2ce8730a21f72a80 may help (related to the redis sentinel support proposal), but I still get occasional timeouts to elasticache when there's low traffic anyway
