### ISSUE TITLE
Dalli does not work with Twemproxy

### ISSUE THREAD

**Issue by icostan** [twitter/twemproxy#194]
Hi,

For some reasons dalli (ruby memcached client) does not work with twemproxy, I always get this response (verbosity 8):

[Wed Feb  5 16:26:02 2014] nc_proxy.c:336 accepted c 9 on p 7 from 'xxx.xxx.xxx.xxx:52009'
[Wed Feb  5 16:26:02 2014] nc_proxy.c:280 accept on p 7 not ready - eagain
[Wed Feb  5 16:26:02 2014] nc_connection.c:324 recv on sd 9 24 of 16336
[Wed Feb  5 16:26:02 2014] nc_memcache.c:712 parsed bad req 1 res 1 type 0 state 0
00000000  80 0b 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010  00 00 00 00 00 00 00 00                            |........|
[Wed Feb  5 16:26:02 2014] nc_core.c:162 recv on c 9 failed: Invalid argument
[Wed Feb  5 16:26:02 2014] nc_core.c:201 close c 9 'xxx.xxx.xxx.xxx:52009' on event FFFF eof 0 done 0 rb 24 sb 0: Invalid argument
[Wed Feb  5 16:26:02 2014] nc_client.c:147 close c 9 discarding pending req 1 len 24 type 0

Looks like the client sends something that is not recognized by twemproxy but dont know what.
Connecting directly to memcached server works just fine.

**Comment by xinuc** [comment]
@manjuraj is there any reason why binary_memcache didn't merged yet?

**Comment by priya23** [comment]
Hi ,
I tried the same thing with binary_memcache branch.still getting the same error

[Tue Aug 11 10:27:54 2015] nc_proxy.c:336 accepted c 8 on p 7 from '10.152.21.14:55415'
[Tue Aug 11 10:27:54 2015] nc_proxy.c:280 accept on p 7 not ready - eagain
[Tue Aug 11 10:27:54 2015] nc_connection.c:324 recv on sd 8 24 of 464
[Tue Aug 11 10:27:54 2015] nc_memcache.c:712 parsed bad req 10 res 1 type 0 state 0
00000000  80 0b 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
00000010  00 00 00 00 00 00 00 00                            |........|
[Tue Aug 11 10:27:54 2015] nc_core.c:163 recv on c 8 failed: Invalid argument
[Tue Aug 11 10:27:54 2015] nc_core.c:202 close c 8 '10.152.21.14:55415' on event FFFF eof 0 done 0 rb 24 sb 0: Invalid argument
[Tue Aug 11 10:27:54 2015] nc_client.c:147 close c 8 discarding pending req 10 len 24 type 0

Can you help Please.
Regards,
Priyanka

**Comment by shapirus** [comment]
Any news on the binary_memcache branch? It's been sitting there waiting to be merged since 2014 :)
