### ISSUE TITLE
Add a test suite

### ISSUE THREAD

**Issue by thedrow** [twitter/twemproxy#197]
Currently twemproxy has almost no tests. I can see that it has some basic smoke tests at https://github.com/twitter/twemproxy/tree/master/scripts but it's not enough.

First of all the smoke tests should run on each build. I don't see a walkthrough for running the smoke tests so it would be nice to have one so I can create a basic build process for twemproxy.

Second of all we should select a testing framework/tool. Functional black box testing is where we should begin so I suggest something BDD oriented. Maybe https://github.com/arnaudbrejeon/cspec which looks maintained.

After we finish blackbox testing we can use something like http://cmocka.org/ for unit testing if there's any value in it.

**Comment by mckelvin** [comment]
:+1:

I guess a unittest test for the C code and a blackbox-test (in python) are both essential.

> not everyone like nosetests, and this test suite need time to complete

What any shortcoming with nosetests? Consider py.test ?

**Comment by TysonAndre** [comment]
I added an extremely minimal standalone C test suite in https://github.com/twitter/twemproxy/blob/master/src/test_all.c and updated src/Makefile.am - it can be run with `make check` - raw test can be seen with `cd src; make test_all; ./test_all`

google-test or another c unit testing framework would probably be an improvement, but I wasn't familiar with how to set them up at the time (without affecting the dependencies or compilation options of the program being tested).

----

It's possible to run the tests in docker with `./travis.sh 3.2` for redis 3.2, though this only covers one platform
