### ISSUE TITLE
feature request: kqueue support

### ISSUE THREAD

**Issue by dropwhile** [twitter/twemproxy#2]
feature request for kqueue support.

```
$ ./configure
....
configure: error: required sys/epoll.h header file is missing
```

It would be nice to be able to use twemproxy/nutcracker while doing development on osx, as well as possible deployment onto FreeBSD. Would it be possible to add kqueue support?

**Comment by vbauer** [comment]
I have the same problem with the current master (c6120fc45749612fb415f9d34502a1ce489ef106):

```
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking sys/epoll.h usability... no
checking sys/epoll.h presence... no
checking for sys/epoll.h... no
configure: error: required sys/epoll.h header file is missing
```
