### ISSUE TITLE
Big memory consumed when using pipeline

### ISSUE THREAD

**Issue by liu21yd** [twitter/twemproxy#203]
Hi all:

```
  we are using twemproxy with redis for sharding. There are 8 instances after proxy.When we used 80 clients, and each one sent about 100 ~ 200 commands one time to the proxy at the same time, the proxy's memory increased so quickly, after about 5 mimitues, it could consume 10G and then crashed.
we have used -m 512 and define NC_IOV_MAX to 512, it didn't work.
```

![nutcracker](https://f.cloud.github.com/assets/6862946/2334666/47988158-a47b-11e3-841d-48ac3b5fd9e8.png)

```
Could anyone help me fix this issue?Thanks.  
```

**Comment by crazyneo-xx** [comment]
Expecting max_memory option to be provided.
I was using one client connection for continuous message sending with no receive action at all(hiredis function modified), nc just stuck within minutes. Memory it used reached the system maximum and was never freed even when I close the connection, and also I can't have any other connection because of OOM issues.
I was wondering, that besides the max_memory option to protect user abusing or overload, should we consider a more graceful way, like trying maintaining a tailq for each connection while all tailqs belong to one memory pool? So that once a connection is closed, we might simply free all the chunk linked to the tailq? 
 It might be a little tricky to decide whether the connection was properly closed or just shortly unnormal state.

**Comment by yongman** [comment]
> @manjuraj ,@charsyam:
> 
> Unfortunately, we applied the patch you suggesting, and ran our tests, it was unuseful.
> 
> void
> mbuf_put(struct mbuf *mbuf)
> {
> //    log_debug(LOG_VVERB, "put mbuf %p len %d", mbuf, mbuf->last - mbuf->pos);
> //
> //    ASSERT(STAILQ_NEXT(mbuf, next) == NULL);
> //    ASSERT(mbuf->magic == MBUF_MAGIC);
> //
> //    nfree_mbufq++;
> //    STAILQ_INSERT_HEAD(&free_mbufq, mbuf, next);
>     mbuf_free(mbuf);
> }
> Besides, based on the above patch, we applied another patch, like this:
> 
> void
> msg_put(struct msg *msg)
> {
>     log_debug(LOG_VVERB, "put msg %p id %"PRIu64"", msg, msg->id);
>     while (!STAILQ_EMPTY(&msg->mhdr)) {
>         struct mbuf *mbuf = STAILQ_FIRST(&msg->mhdr);
>         mbuf_remove(&msg->mhdr, mbuf);
>         mbuf_put(mbuf);
>     }
> //    nfree_msgq++;
> //    TAILQ_INSERT_HEAD(&free_msgq, msg, m_tqe);
>     msg_free(msg);
> }
> It also didn't work.
> 
> But, at this time, we checked and recorded the stats of twemproxy in the process of the test, this maybe could help you to analyze and fix this issue and give us some advice.
> 
> Fri Mar 7 19:05:51 CST 2014
> {"service":"nutcracker", "source":"192.168.1.110", "version":"0.3.0", "uptime":60, "timestamp":1394190351, "writer": {"client_eof":0, "client_err":0, "client_connections":0, "server_ejects":0, "forward_error":0, "fragments":0, "192.168.1.110:6001": {"server_eof":0, "server_err":0, "server_timedout":0, "server_connections":0, "server_ejected_at":0, "requests":0, "request_bytes":0, "responses":0, "response_bytes":0, "in_queue":0, "in_queue_bytes":0, "out_queue":0, "out_queue_bytes":0},"192.168.1.110:6002": {"server_eof":0, "server_err":0, "server_timedout":0, "server_connections":0, "server_ejected_at":0, "requests":0, "request_bytes":0, "responses":0, "response_bytes":0, "in_queue":0, "in_queue_bytes":0, "out_queue":0, "out_queue_bytes":0}}}
> Fri Mar 7 19:05:54 CST 2014
> {"service":"nutcracker", "source":"192.168.1.110", "version":"0.3.0", "uptime":63, "timestamp":1394190354, "writer": {"client_eof":0, "client_err":0, "client_connections":240, "server_ejects":0, "forward_error":0, "fragments":0, "192.168.1.110:6001": {"server_eof":0, "server_err":0, "server_timedout":0, "server_connections":1, "server_ejected_at":0, "requests":290165, "request_bytes":26812704, "responses":275245, "response_bytes":1133134, "in_queue":16, "in_queue_bytes":2736, "out_queue":14904, "out_queue_bytes":1389370},"192.168.1.110:6002": {"server_eof":0, "server_err":0, "server_timedout":0, "server_connections":1, "server_ejected_at":0, "requests":236117, "request_bytes":22729182, "responses":235997, "response_bytes":975032, "in_queue":31, "in_queue_bytes":5189, "out_queue":89, "out_queue_bytes":9454}}}
> Fri Mar 7 19:06:30 CST 2014
> {"service":"nutcracker", "source":"192.168.1.110", "version":"0.3.0", "uptime":99, "timestamp":1394190390, "writer": {"client_eof":0, "client_err":0, "client_connections":400, "server_ejects":0, "forward_error":0, "fragments":0, "192.168.1.110:6001": {"server_eof":0, "server_err":0, "server_timedout":0, "server_connections":1, "server_ejected_at":0, "requests":13205991, "request_bytes":1211720915, "responses":3418198, "response_bytes":14063533, "in_queue":9758660, "in_queue_bytes":895414027, "out_queue":29133, "out_queue_bytes":2270239},"192.168.1.110:6002": {"server_eof":0, "server_err":0, "server_timedout":0, "server_connections":1, "server_ejected_at":0, "requests":6862631, "request_bytes":751595146, "responses":3256944, "response_bytes":13656769, "in_queue":3580334, "in_queue_bytes":394467044, "out_queue":25353, "out_queue_bytes":2776957}}}
> Fri Mar 7 19:06:33 CST 2014
> {"service":"nutcracker", "source":"192.168.1.110", "version":"0.3.0", "uptime":102, "timestamp":1394190393, "writer": {"client_eof":0, "client_err":0, "client_connections":400, "server_ejects":1, "forward_error":106460, "fragments":0, "192.168.1.110:6001": {"server_eof":0, "server_err":1, "server_timedout":0, "server_connections":0, "server_ejected_at":1394190392234820, "requests":13209106, "request_bytes":1211992601, "responses":3418198, "response_bytes":14063533, "in_queue":0, "in_queue_bytes":0, "out_queue":0, "out_queue_bytes":0},"192.168.1.110:6002": {"server_eof":0, "server_err":0, "server_timedout":0, "server_connections":1, "server_ejected_at":0, "requests":7463043, "request_bytes":810447031, "responses":3421994, "response_bytes":14351538, "in_queue":4015739, "in_queue_bytes":434603174, "out_queue":25310, "out_queue_bytes":2988179}}}
> Fri Mar 7 19:08:38 CST 2014
> {"service":"nutcracker", "source":"192.168.1.110", "version":"0.3.0", "uptime":227, "timestamp":1394190518, "writer": {"client_eof":0, "client_err":0, "client_connections":400, "server_ejects":53, "forward_error":126961, "fragments":0, "192.168.1.110:6001": {"server_eof":0, "server_err":53, "server_timedout":0, "server_connections":0, "server_ejected_at":1394190510571647, "requests":14035498, "request_bytes":1287899296, "responses":3418198, "response_bytes":14063533, "in_queue":286718, "in_queue_bytes":26249247, "out_queue":0, "out_queue_bytes":0},"192.168.1.110:6002": {"server_eof":0, "server_err":0, "server_timedout":0, "server_connections":1, "server_ejected_at":0, "requests":21767898, "request_bytes":2215822059, "responses":21031903, "response_bytes":87507329, "in_queue":702210, "in_queue_bytes":71225864, "out_queue":33785, "out_queue_bytes":3300524}}}

I think the reason memory not freed after `mbuf_free(mbuf)` is the malloc mechanism of `brk` resulting memory fragments. Call `msg_free` in `msg_put` will result in memory freed.
