### ISSUE TITLE
Can this be load balanced for redundancy?

### ISSUE THREAD

**Issue by matthewdresden** [twitter/twemproxy#220]
If so, can a general high-level recommended route be posted here? I will post how I did it in detail after I have it working. I have access to F5 LTMs, just about anything else.

I am building a clustered demo of LogStash with redis clusters for my Company Cengage Learning in an effort to  offset or replace the extremely expensive Splunk tool we are currently using.

I am not looking for step by step how to, just a path that the developers think would work or better yet had tested.

**Comment by pank7** [comment]
@rhoml can you tell me more on how you are haproxy on twemproxy?

**Comment by rhoml** [comment]
@pank7 what we do basically is to setup haproxy on TCP mode in front of twemproxy and we have a pool of twemproxy configured on each endpoint. This ensures that the requests are balanced and in case of any failure haproxy will take them out of the pool. 
pretty basic straight forward.

**Comment by TysonAndre** [comment]
> what we do basically is to setup haproxy on TCP mode in front of twemproxy and we have a pool of twemproxy configured on each endpoint. This ensures that the requests are balanced and in case of any failure haproxy will take them out of the pool.
pretty basic straight forward.

Yes, it can be load balanced in any of the following ways

1. HAProxy in tcp mode to random instances works
2. If there are a lot of independent connections being made (e.g. php+apache) it's useful to choose a single random twemproxy instance (immediately before connecting) to connect to
3. Alternately, you can pass the full list of addresses of twemproxy instances to the application using twemproxy, if there is a single client (or fixed-size client pool) in an application uses long-lived connections (e.g. java) 

Twemproxy is single threaded (the stats thread only processes requests on the stats port), so it will hit a bottleneck at 100% cpu - in applications that heavily use memcached the number of instances of twemproxy I've used is around 1/10th of the cpus (e.g. on a 96-core machine, use 10 nutcracker instances).
