### ISSUE TITLE
why twemproxy not support multi/exec

### ISSUE THREAD

**Issue by jackiesun8** [twitter/twemproxy#279]
why twemproxy not support multi/exec?

**Comment by zmijevik** [comment]
@idning Is it possible to provide transaction operations to a pool with a sole instance? If there is a sole instance there is no sharding and therefore atomic transaction can be guaranteed. This way I can route all transaction dependent queries to the appropriate pool (with one instance) and continue using smitty or other twempoxy failover mechanisms for this pool.
