### ISSUE TITLE
twemproxy not set keepalive for client fd?

### ISSUE THREAD

**Issue by jinhao** [twitter/twemproxy#306]
recently my twemproxy machine connection reach the limit of our monitor threshold， i found twemproxy have many dead connection, did twemproxy have tcp keepalive switch?

**Comment by manjuraj** [comment]
this might be because connections are in TIME_WAIT state. You can change it at the kernel level. See https://github.com/twitter/twemproxy/blob/master/notes/socket.txt#L61

**Comment by rockysoar** [comment]
@manjuraj @jinhao 
1. tcp keep alive (kernel defined) is used in Twemproxy:
https://github.com/vipshop/twemproxy-vip/wiki/twemproxy-maintained-and-used-at-vipshop

2. kernel defined keep alive:
int setsockopt(int s, int level, int optname, const void *optval, socklen_t optlen)

The first parameter is the socket, previously created with the socket(2); the second one must be SOL_SOCKET, and the third must be SO_KEEPALIVE. The fourth parameter must be a boolean integer value, indicating that we want to enable the option, while the last is the size of the value passed before.

3. But something wrong in Twemproxy:
`33 redis.51fanli.it-6390:
34     listen: /var/run/nutcracker/nutcracker_redis.51fanli.it_6390.sock
35     hash: md5
36     distribution: modula
37     auto_eject_hosts: false
38     server_connections: 1
39     preconnect: true
40     timeout: 400
41     redis: true
42     tcpkeepalive: true
43     tcpkeepidle: 800
44     tcpkeepcnt: 3 
45     tcpkeepintvl: 60
46     servers:
47         - redis.51fanli.it:6390:1`

[2016-07-22 11:17:50.927] nc.c:187 nutcracker-0.4.1 built for Linux 2.6.32-042stab093.4 x86_64 started on pid 6204
[2016-07-22 11:17:50.927] nc.c:192 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one
[2016-07-22 11:17:50.928] nc_conf.c:523 conf: directive "tcpkeepalive" is unknown
[2016-07-22 11:17:50.929] nc.c:198 done, rabbit done
