### ISSUE TITLE
Add two command into README.md

### ISSUE THREAD

**Issue by simon-xia** [twitter/twemproxy#307]
when I installed twemproxy on my Ubuntu 14.04, it stoped at the step
 > autoreconf -fvi

With the help of Google, I found that it was because some lack of depended package.  

So I suggested to add the following two steps into "Build" part of README.md, and they can be named as 'Before build'

    sudo apt-get install automake 
    sudo apt-get install libtool

**Comment by manjuraj** [comment]
done
