### ISSUE TITLE
Can I use twemproxy with redis_auth conf?

### ISSUE THREAD

**Issue by sjang** [twitter/twemproxy#310]
Hello~
I am trying to use twemproxy in my office. My main job is a kind of maintenance for a service which can provide a cloud storage for Korean. I mean most of users are Korean.

I have a questions about twemproxy for redis.

Is redis_auth available please? 
(I think that when nutcracker is executed, redis AUTH command is not sent from twem to a original redis server.)

That's my procedure:

I downloaed nutcracker from git master.
I built it and I executed it with redis_auth in my yml file like below.

```
$ cat nutcracker.yml
session:
  listen: 0.0.0.0:7373
  hash: fnv1_64
  distribution: ketama
  preconnect: true
  redis: true
  server_retry_timeout: 2000
  server_failure_limit: 10
  redis_auth: "tcd!@#1"
  servers:
   - 172.10.3.5:6379:1 redis_master
```

And
```
My server diagram: client -> twem -> redis_master
```

The redis_master has the required pass(tcd...). So, I wrote my yml file with redis_auth. I tested a redis command, simple SET. But, NOAUTH message from redis_master maybe.

redis command:
```
$ redis-cli -p 7373 SET key1 value1
(error) NOAUTH Authentication required
```

and nutcracker stdout message:
```
[2015-01-08 09:27:27.308] nc_proxy.c:366 accepted c 8 on p 7 from '127.0.0.1:51065'
[2015-01-08 09:27:27.309] nc_request.c:96 req 1 done on c 8 req_time 0.061 msec type REQ_REDIS_SET narg 3 req_len 35 rsp_len 33 key0 'key1' peer '127.0.0.1:51065' done 1 error 0
[2015-01-08 09:27:27.309] nc_core.c:237 close c 8 '127.0.0.1:51065' on event 00FF eof 1 done 1 rb 35 sb 33
```

So, I think that when nutcracker is executed, redis AUTH command is not sent from twemproxy to a original redis server.

Please, Is redis_auth supported?

Thank you in advanced.

**Comment by charsyam** [comment]
@sjang did you send auth command from your client?
it needs

**Comment by sjang** [comment]
@charsyam I tested twice with -a option and without -a option in redis-cli like below:

```
$ redis-cli -p 7373 SET key1 value1
(error) NOAUTH Authentication required

$ redis-cli -a 'tcd!@#1' -p 7373 SET key1 value1
(error) NOAUTH Authentication required
```

The result is same.

**Comment by charsyam** [comment]
@sjang could you retry it to remove quote in your yml
ex)
redis_auth: abcd

and also redis-cli -a abcd
without quote and double quote

**Comment by sjang** [comment]
@charsyam I tested twice with -a option and without -a option using redis-cli like below:

```
$ redis-cli -p 7373 SET key1 value1
(error) NOAUTH Authentication required

redis-cli -a 'tcd!@#1' -p 7373 SET key1 value1
(error) NOAUTH Authentication required
```

The result is same.

I think that redis_auth is the authentication between twem and original redis.
Is that wrong?

From Readme.md:
```
redis_auth: Authenticate to the Redis server on connect.
```

and I understand that twemproxy is not supported for AUTH command from client.

Please, help~. It is not easy to say removing pass to clients.

Thanks a lot.

**Comment by sjang** [comment]
I misunderstood about AUTH support on twem.
I thought that twem is not supporting in terms of redis AUTH command. But, it is wrong. It is necessary to use AUTH command in redis client side, too. 
@charsyam's redis_auth is perfect. 
Thank you very much.

**Comment by idning** [comment]
cool:)

**Comment by letdeveloper** [comment]
I had the same misunderstood than Sjang.

**Comment by Lalio** [comment]
so,  how do you fix it in finally? it confuse me

**Comment by sjang** [comment]
Hi Lalio,

I did git clone.(I did not use the source file by http download provided by github.)

The clone includes the redis_auth function on twemproxy conf file.

It works very well.

Thank you~

**Comment by ciarans** [comment]
Guys, im having some problems.

So just to be clear, I have the following yml

```
leaf:
  listen: 127.0.0.1:22121
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  redis_auth: MyRedisPassword
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - ec2-XX-XX-XX-XX.XX-XX-X.compute.amazonaws.com:6379:1
```
The password relates to the redis.conf on my ec2 instance, however I keep getting  *NOAUTH Authentication required*

Is  the redis_auth an Auth for twemproxy or my ec2 instance?

I can connect to my ec2 instance with the following command no problem.
```
Ciarans-iMac:~ ciaran$ redis-cli -h ec2-XX-XX-XX-XX.XX-XX-X.compute.amazonaws.com -p 6379
ec2-52-210-189-128.eu-west-1.compute.amazonaws.com:6379> auth MyRedisPassword
OK 
```

**Comment by sjang** [comment]
Hi~
It is a sort of version of the twemproxy.
Download the twemproxy source from the github server using git clone, not zipfile.
The code is added by @charsyam.
Good luck~

**Comment by ciarans** [comment]
Hi @sjang I have downloaded and got twemproxy running in docker

```dockerfile
RUN echo "==> Install TwemProxy/Nutcracker..."  && \
    cd /opt && \
    git clone https://github.com/twitter/twemproxy.git && \
	cd twemproxy && \
	autoreconf -fvi && \
    CFLAGS="-ggdb3 -O1" ./configure --enable-debug=full && \
    make clean && \
    make install && \
    ln -sf /opt/twemproxy/src/nutcracker /usr/local/bin/nutcracker && \
    nutcracker --version
```

Im just confused about what redis_auth relates to

**Comment by charsyam** [comment]
@ciarans Does your app send auth command to twemproxy? you should send auth command to twemproxy :)

**Comment by ciarans** [comment]
@charsyam No my app does not send it to twemproxy, however my ec2 instance running redis needs the auth command.

Im trying to use twemproxy as a redis cache for Google PageSpeed. Google PageSpeed does not support AUTH, so my idea was to use twemproxy, without auth to connect my Redis instances that require auth.

```nginx
#TwemProxy without Auth
pagespeed RedisServer "127.0.0.1:22121";
```

I was thinking that I could then receive the command via TwemProxy and then auth into my ec2 instance.

```
twemproxy --> AUTH --> REDIS_EC2
```

Is this possible? Thanks for your help

**Comment by charsyam** [comment]
@ciarans No. Your app must send auth to twemproxy like just using redis directly.
so it is like this

Your app -> AUTH#1 -> Twemporxy -> AUTH#2 -> REDIS_EC2
in AUTH#1, Twemproxy checks your password is correct.
in AUTH#2, Twemproxy sends password to Redis with AUTH Command.

**Comment by sjang** [comment]
@ciarans 
I did not fully understand your idea. But I think it is connection problem.
As far as I know, Redis auth is valid per connection with auth passed.

**Comment by ciarans** [comment]
@charsyam Ok thanks for clearing that up. Back to the drawing board for me :).
