### ISSUE TITLE
EVAL mishandling Multi Bulk reply of Simple String(s)

### ISSUE THREAD

**Issue by quix00** [twitter/twemproxy#323]
When trying to return the result of multiple Redis HMSET commands within a lua table, the proxy returns ```ERR Invalid Argument``` even though the command succeeds.

Example Case:
```
127.0.0.1:10001> eval "return redis.call('HMSET', KEYS[1], ARGV[1], ARGV[2])" 1 test key value
OK
```

```
127.0.0.1:10001> eval "return {redis.call('HMSET', KEYS[1], ARGV[1], ARGV[2])}" 1 test key value
(error) ERR Invalid Argument
```

I've tested with a36fdae and Redis 2.8.19

**Comment by charsyam** [comment]
@quix00 could you try this version?
https://github.com/charsyam/twemproxy/tree/feature/issue-323

**Comment by quix00** [comment]
@charsyam Yup, works like a charm! Thanks

**Comment by idning** [comment]
https://github.com/twitter/twemproxy/pull/326 is already merged! 

thanks guys
