### ISSUE TITLE
twemproxy memcached

### ISSUE THREAD

**Issue by aia06** [twitter/twemproxy#325]
I have configure the memcached  cluster use twemproxy, there is a strange phenomena in twemproxy running which memcached didn't work use 11211 port on the server with twemproxy.And I have to create another memcached use 11212 port on the same server ,then it's worked  properly.How can I understand ?  
my nutcracker.yml :
gamma:
  listen: 0.0.0.0:11112
  hash: fnv1a_64
  distribution: ketama
  timeout: 400
  backlog: 1024
  preconnect: true
  auto_eject_hosts: true
  server_retry_timeout: 2000
  server_failure_limit: 2
  servers:
   - 127.0.0.1:11211:1
   - 127.0.0.1:11212:1
   - 172.16.0.235:11211:1

**Comment by manjuraj** [comment]
this might be the issue of multiple process using the same port. You can debug it using "netstat" or "ss" command line tool
