### ISSUE TITLE
FFFF Invalid argument

### ISSUE THREAD

**Issue by imton** [twitter/twemproxy#328]
Hi guys,

I can't make this work with redis 2.6 neither 2.8. I tried it on my mac and on a clean ubuntu.

Always get this error, no matter what I do
````
➜ twemproxy-docker git:(master) ✗ redis-benchmark -h 192.168.59.103 -p 22121
Error: Server closed the connection
````

````
[2015-03-06 18:34:33.247] nc_core.c:237 close c 9 '192.168.59.3:58173' on event FFFF eof 0 done 0 rb 6 sb 0: Invalid argument
[2015-03-06 18:34:33.247] nc_core.c:237 close c 10 '192.168.59.3:58174' on event FFFF eof 0 done 0 rb 6 sb 0: Invalid argument
[2015-03-06 18:34:33.247] nc_core.c:237 close c 11 '192.168.59.3:58175' on event FFFF eof 0 done 0 rb 6 sb 0: Invalid argument
````
More logs:
https://gist.github.com/imton/22631711475880cda096

Hours into this, help?

Thanks

**Comment by manjuraj** [comment]
See this for supported commands: https://github.com/twitter/twemproxy/blob/master/notes/redis.md

if you want to run redis benchmark do this: https://github.com/twitter/twemproxy/blob/master/notes/redis.md#redis-benchmark-against-nutcracker-proxing-redis-server

**Comment by imton** [comment]
I am sorry manjuraj, nothing is working. No redis-cli, any command fails

**Comment by imton** [comment]
@manjuraj thank you! may you help me how to benchmark getting real keys balanced over all instances? redis-benchmark thru the proxy only hits one, not balancing.

**Comment by manjuraj** [comment]
@imton that might be because all your keys looks the same. Sharing is based on hashing the keys. Your key strings must be uniformly random for keys to go to different servers
