### ISSUE TITLE
Mset not strong enough.Wrong typing will cause core dump.

### ISSUE THREAD

**Issue by shenhang** [twitter/twemproxy#332]
Hi idning,I found a bug about mset. 
If the key is typed without key ,the process will abort.

**Comment by shenhang** [comment]
Line 1182 ,in file src/proto/nc_redis.c of release 0.4.0,should be modified as "go to error"

**Comment by hit9** [comment]
I meet the same error. 

Mset with invalid (3, 5, etc) will make twemproxy core dump.

**Comment by idning** [comment]
hi, all, are you using tag 0.4.0? 

this bug is already fixed in Nov 6, 2014 (https://github.com/twitter/twemproxy/commit/591b25eaabb3a2bd345a3ce7800fe5728e743dd1)

please try the master.

**Comment by idning** [comment]
fixed in https://github.com/twitter/twemproxy/commit/f1645b04fcdab568c374dca459f1ebb74a1c02ae
