### ISSUE TITLE
best "server_connections" setting number for memcached

### ISSUE THREAD

**Issue by deep011** [twitter/twemproxy#339]
Hi, i want to know what is the best "server_connections" setting number for memcached.
I think "server_connections: 1" is the best, because the twemproxy is single thread. Is it correct?

**Comment by charsyam** [comment]
@deep011 if you use some commands that take long time.
at that, it is better to set server_connections > 1,
but, if you not, server_connections: 1 is also good.

**Comment by manjuraj** [comment]
https://github.com/twitter/twemproxy/blob/master/notes/recommendation.md#server_connections--1
