### ISSUE TITLE
timeout setting promblem

### ISSUE THREAD

**Issue by deep011** [twitter/twemproxy#340]
Hi, i want confirm a question.
1. My client is long connection and client set timeout itself, 
2. Twemproxy configuration:
twemproxy1:
  listen: 127.0.0.1:22135
  hash: fnv1a_64
  hash_tag: "{}"
  distribution: ketama
  auto_eject_hosts: true
  server_connections: 100
  server_failure_limit: 3
  server_retry_timeout: 30000
  redis: false
  servers:
  - 127.0.0.1:23401:1 server1
  - 127.0.0.1:23401:1 server2
  - 127.0.0.1:23401:1 server3

Now, if one mc always timeout, the other two mc are ok, will my all requests to twemproxy maybe are timeout?(all the requests cross by my one long connection)

**Comment by manjuraj** [comment]
I guess this is your question. Let say you send `mget key1 key2 key3`.
key1 goes to server1
key2 goes to server2
key3 goes to server3

if you don't hear back from server1 because connection timedout, the entire mget request times out. We send back `SERVER_ERRROR Connection timedout\r\n` to the client, even though we have a valid response for key2 and key3

However, if you send `mget key2 key3` and assuming server2 and server3 don't time out, we would forward the response from server to client

**Comment by deep011** [comment]
Thank for this reply.
Look the follow code in the twemproxy
 
if (req_done(c_conn, TAILQ_FIRST(&c_conn->omsg_q))) {
        status = event_add_out(ctx->evb, c_conn);
        if (status != NC_OK) {
            c_conn->err = errno;
        }
    }

if (pmsg == NULL || !req_done(conn, pmsg)) {
        /* nothing is outstanding, initiate close? */
        if (pmsg == NULL && conn->eof) {
            conn->done = 1;
            log_debug(LOG_INFO, "c %d is done", conn->sd);
        }
		status = event_del_out(ctx->evb, conn);
        if (status != NC_OK) {
            conn->err = errno;
        }
        return NULL;
    }

If the first msg is not done in one client connection, the back msgs will never response to client. 
If twemproxy did not setting timeout, and the first msg always not come back from mc, the other msgs in this client connection also can not response to client, right?
Then the situation i described above will be appear, i don't know what i say is right or not.

**Comment by deep011** [comment]
And at this time, the twemproxy's memory will increase quickly.

**Comment by manjuraj** [comment]
Yeah. Adding timeout is critical. Have you read the recommendation.md section about timeout?

**Comment by deep011** [comment]
Yeah, i had read the recommendation.md before, but i just know one mc timeout can effect other mc responses. Then, thank you for this quick reply and we will add timeout for all our twemproxy, thanks again! ;)
