### ISSUE TITLE
Re-balancing Keys across Redis nodes?

### ISSUE THREAD

**Issue by veselinkantsev** [twitter/twemproxy#345]
Hello, 
I run 3 Redis nodes behind a Twemproxy daemon, where node 'A'  seems to now take most of the load with 'B' and 'C' idling. 

I suspect this is because of Twemproxy ejecting 'B' and 'C" hosts at some stage due to temporary network outages and rerouting most keys to 'A'. 

- Would Twemproxy keep using 'A' for those keys even after 'B' and 'C' are back in operation?
- If so, what is the recommended way to re-balance the rerouted(or all) keys?
- Could I simply reload the twemproxy service, so it starts routing keys evenly as before the ejections?

**Comment by manjuraj** [comment]
twemproxy would add the ejected host (when auto_eject_host: true) back to the ring after server_retry_timeout.

I suspect, most of the load is being routed to node 'A' because the key space is not uniform and all the keys are being hashed to node A

**Comment by veselinkantsev** [comment]
@manjuraj 
Hi, given that the ejected hosts have been added back to the ring what happens to any keys which have been moved to a different node in the mean time?

In my case, I'd imagine whilst nodes 'B' and 'C' were out, their keys got hashed to 'A'.
Now that they are back in the ring however, do the keys remain hashed to 'A'?

**Comment by manjuraj** [comment]
twemproxy doesn't do rebalancing. This talk talks about how to run twemproxy in production: http://redisconference.com/video/running-twemproxy-in-production/?iframe=yes

**Comment by veselinkantsev** [comment]
@manjuraj Thank you Manju.
