### ISSUE TITLE
twemproxy +redis  twemporxy could not drop fail redis instance

### ISSUE THREAD

**Issue by wxfxn2000** [twitter/twemproxy#347]
hello ,i was testing twemproxy +redis ,the conf is :
alpha:
  listen: 0.0.0.0:9999
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  server_retry_timeout: 3000
  server_failure_limit: 1
  servers:
   - 192.168.1.217:6379:1
   - 192.168.1.218:6379:1
   - 192.168.1.219:6379:1

my python scripts to test this twemproxy+redis:
    [root@douguo211 python]# cat pythonredis.py 
#!/usr/bin/env python
#coding=utf8
import redis
r=redis.Redis(host='192.168.1.216',port=9999,db=0)
for i in range(1,10000):
   r.set("foo%d" %i,"goo%d" %i);

when i shutdown 192.168.1.219: 6379 
i found a error every 3 second ,i repeated  to  receive the  errors:connection refused
and tail -f twemproxy_error log ：
[2015-04-03 17:01:22.608] nc_core.c:237 close s 10 '192.168.1.219:6379' on event FF00FF eof 0 done 0 rb 0 sb 0: Connection refused
[2015-04-03 17:02:48.163] nc_core.c:237 close s 10 '192.168.1.219:6379' on event FF00FF eof 0 done 0 rb 0 sb 0: Connection refused

when i change server_retry_timeout: 30000
i found a error every 30 second,i repeated  to  receive the errors:connection refused
and tail -f twemproxy_error log ：

i think  the twemproxy didn't drop fail redis server,when the time =server_retry_timeout,twemproxy still to connect the fail redis server.
i don't understand ,where is error??
my redis version is 2.6.13,maybe redis version is too old???or my twemproxy config is error????
can you help me ,thanks

**Comment by manjuraj** [comment]
read this: https://github.com/twitter/twemproxy/blob/master/notes/recommendation.md and watch this: http://redisconference.com/video/running-twemproxy-in-production/
