### ISSUE TITLE
Random hashing

### ISSUE THREAD

**Issue by jhmartin** [twitter/twemproxy#348]
I am looking at using twemproxy to loadbalance  incoming LogStash data across multiple redis instances.  Logstash uses always to one key 'logstash'.  Is there a mechanism to have twemproxy round-robin across the known redis instances rather than pin this key to just one redis instances?

**Comment by manjuraj** [comment]
use `distribution: random` in your config file

**Comment by charsyam** [comment]
@jhmartin Do you mean your redis instances have all same data to distribute read operations for just load balancing not for writing?
and then just use random as @manjuraj mentioned :)

**Comment by jhmartin** [comment]
This is write-specific (rpush).  I want each rpush to go to a random redis regardless of key, it sounds like 'random' will do that.

The read-side won't use twemproxy; those Logstash nodes will be aware of each Redis directly.

**Comment by manjuraj** [comment]
random should be good for your usecase

**Comment by jhmartin** [comment]
Sounds good, thank you.
