### ISSUE TITLE
something wrong on ubuntu 14.04 

### ISSUE THREAD

**Issue by silviucpp** [twitter/twemproxy#356]
Hello,

I installed twemproxy on ubuntu 14.04 64 bit from https://launchpad.net/~twemproxy/+archive/ubuntu/stable

I have the following config:

etc/init/nutcracker.yml                                                                                                                 

<pre>
memcached:
  listen: 0.0.0.0:22123
  hash: fnv1a_64
  distribution: ketama
  timeout: 400
  backlog: 1024
  preconnect: true
  auto_eject_hosts: true
  server_connections: 5
  server_retry_timeout: 10000
  server_failure_limit: 3
  servers:
   - 127.0.0.1:11211:1000
</pre>
Using the following code in PHP:

<pre>
$Memcached = new Memcached();
$Memcached->addServer('127.0.0.1', 22123);
$version = $Memcached->getVersion();
$Memcached->set('key', "test", 5);
var_dump($Memcached->get('key'));      // boolean false
var_dump($Memcached->getResultCode()); // int 0 which is  Memcached::RES_SUCCESS  
echo "Server's version: ".json_encode($version)."<br/>\n";

</pre>

I get:

<pre>
Server's version: {"127.0.0.1:22123":"255.255.255"}<br/>
bool(false)
int(16)
</pre>

Connecting the same code to port 11211 where memcache is listening is working perfect.. where I'm wrong?

I suspected the yaml file is not loaded properly but using nutcracker --conf-file=/etc/init/nutcracker.yml -v 11 I have the same results..

Silviu

**Comment by charsyam** [comment]
@silviucpp 
Could you show me the log of twemproxy?
and Could you remove "$version = $Memcached->getVersion();" line? 
I think memcached can't process version command. so twemproxy close the connection with php.
just check this. :)

**Comment by silviucpp** [comment]
@charsyam thx a lot removing the version line fixed the problem .

Seems none of php5-memcached and php5-memcache is not working if you ask for version.

Silviu
