### ISSUE TITLE
Memcached supported commands

### ISSUE THREAD

**Issue by Ragazzo** [twitter/twemproxy#365]
Is there any list of supported commands like it is done for [redis](https://github.com/twitter/twemproxy/blob/master/notes/redis.md)? Currently in file for [memcached](https://github.com/twitter/twemproxy/blob/master/notes/memcache.txt) there is a note about `flush_all` that it works, but it really does not flush anything. So is this command supported or not?

**Comment by manjuraj** [comment]
flush_all is not supported. I updated the docs. See: https://github.com/twitter/twemproxy/blob/master/notes/memcache.md
