### ISSUE TITLE
Got Error: Server closed the connection

### ISSUE THREAD

**Issue by lscgzwd** [twitter/twemproxy#374]
I used the latest source build.

mysql yml config file:

[root@10-10-13-39 ~]# cat /usr/local/twemproxy/conf/nutcracker.yml 
leaf:
  listen: /dev/shm/redis
  hash: fnv1a_64
  preconnect: true
  distribution: ketama
  auto_eject_hosts: true
  server_retry_timeout: 30000
  server_failure_limit: 3
  servers:
   - 127.0.0.1:6379:1

start command:
[root@10-10-13-39 twemproxy]# /usr/local/twemproxy/sbin/nutcracker -c /usr/local/twemproxy/conf/nutcracker.yml -p /usr/local/twemproxy/run/redisproxy.pid 
[2015-06-17 23:17:51.632] nc.c:187 nutcracker-0.4.0 built for Linux 2.6.32-431.11.7.el6.ucloud.x86_64 x86_64 started on pid 13765
[2015-06-17 23:17:51.633] nc.c:192 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one

redis-cli:

[root@10-10-13-39 ~]# redis-cli -s /dev/shm/redis
redis /dev/shm/redis> set a 0
Error: Server closed the connection
redis /dev/shm/redis> select 0
Error: Server closed the connection
redis /dev/shm/redis> SET A 0
Error: Server closed the connection
redis /dev/shm/redis> SELECT 0
Error: Server closed the connection
redis /dev/shm/redis> auth
Error: Server closed the connection

strace log:

Process 13765 attached - interrupt to quit
epoll_wait(4, {{EPOLLIN, {u32=12753264, u64=12753264}}}, 1024, 30000) = 1
accept(7, 0, NULL)                      = 8
fcntl(8, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(8, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=12753536, u64=12753536}}) = 0
accept(7, 0, NULL)                      = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(4, {{EPOLLOUT, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
epoll_ctl(4, EPOLL_CTL_MOD, 8, {EPOLLIN|EPOLLET, {u32=12753536, u64=12753536}}) = 0
epoll_wait(4, {{EPOLLIN, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
gettimeofday({1434554334, 844951}, NULL) = 0
read(8, "*1\r\n$3\r\nset\r\n", 16336)   = 13
getpeername(8, {sa_family=AF_FILE, NULL}, [2]) = 0
epoll_ctl(4, EPOLL_CTL_DEL, 8, NULL)    = 0
gettimeofday({1434554334, 845105}, NULL) = 0
close(8)                                = 0
epoll_wait(4, {{EPOLLIN, {u32=12753264, u64=12753264}}}, 1024, 30000) = 1
accept(7, 0, NULL)                      = 8
fcntl(8, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(8, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=12753536, u64=12753536}}) = 0
accept(7, 0, NULL)                      = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(4, {{EPOLLOUT, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
epoll_ctl(4, EPOLL_CTL_MOD, 8, {EPOLLIN|EPOLLET, {u32=12753536, u64=12753536}}) = 0
epoll_wait(4, {{EPOLLIN, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
gettimeofday({1434554334, 845443}, NULL) = 0
read(8, "*1\r\n$3\r\nset\r\n", 16336)   = 13
getpeername(8, {sa_family=AF_FILE, NULL}, [2]) = 0
epoll_ctl(4, EPOLL_CTL_DEL, 8, NULL)    = 0
gettimeofday({1434554334, 845572}, NULL) = 0
close(8)                                = 0
epoll_wait(4, {{EPOLLIN, {u32=12753264, u64=12753264}}}, 1024, 30000) = 1
accept(7, 0, NULL)                      = 8
fcntl(8, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(8, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=12753536, u64=12753536}}) = 0
accept(7, 0, NULL)                      = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(4, {{EPOLLOUT, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
epoll_ctl(4, EPOLL_CTL_MOD, 8, {EPOLLIN|EPOLLET, {u32=12753536, u64=12753536}}) = 0
epoll_wait(4, {{EPOLLIN, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
gettimeofday({1434554339, 180301}, NULL) = 0
read(8, "*3\r\n$3\r\nset\r\n$1\r\na\r\n$1\r\n0\r\n", 16336) = 27
getpeername(8, {sa_family=AF_FILE, NULL}, [2]) = 0
epoll_ctl(4, EPOLL_CTL_DEL, 8, NULL)    = 0
gettimeofday({1434554339, 180432}, NULL) = 0
close(8)                                = 0
epoll_wait(4, {{EPOLLIN, {u32=12753264, u64=12753264}}}, 1024, 30000) = 1
accept(7, 0, NULL)                      = 8
fcntl(8, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(8, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=12753536, u64=12753536}}) = 0
accept(7, 0, NULL)                      = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(4, {{EPOLLOUT, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
epoll_ctl(4, EPOLL_CTL_MOD, 8, {EPOLLIN|EPOLLET, {u32=12753536, u64=12753536}}) = 0
epoll_wait(4, {{EPOLLIN, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
gettimeofday({1434554342, 212131}, NULL) = 0
read(8, "*2\r\n$6\r\nselect\r\n$1\r\n0\r\n", 16336) = 23
getpeername(8, {sa_family=AF_FILE, NULL}, [2]) = 0
epoll_ctl(4, EPOLL_CTL_DEL, 8, NULL)    = 0
gettimeofday({1434554342, 212235}, NULL) = 0
close(8)                                = 0
epoll_wait(4, {{EPOLLIN, {u32=12753264, u64=12753264}}}, 1024, 30000) = 1
accept(7, 0, NULL)                      = 8
fcntl(8, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(8, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=12753536, u64=12753536}}) = 0
accept(7, 0, NULL)                      = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(4, {{EPOLLOUT, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
epoll_ctl(4, EPOLL_CTL_MOD, 8, {EPOLLIN|EPOLLET, {u32=12753536, u64=12753536}}) = 0
epoll_wait(4, {{EPOLLIN, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
gettimeofday({1434554345, 771093}, NULL) = 0
read(8, "*3\r\n$3\r\nSET\r\n$1\r\nA\r\n$1\r\n0\r\n", 16336) = 27
getpeername(8, {sa_family=AF_FILE, NULL}, [2]) = 0
epoll_ctl(4, EPOLL_CTL_DEL, 8, NULL)    = 0
gettimeofday({1434554345, 771207}, NULL) = 0
close(8)                                = 0
epoll_wait(4, {{EPOLLIN, {u32=12753264, u64=12753264}}}, 1024, 30000) = 1
accept(7, 0, NULL)                      = 8
fcntl(8, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(8, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=12753536, u64=12753536}}) = 0
accept(7, 0, NULL)                      = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(4, {{EPOLLOUT, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
epoll_ctl(4, EPOLL_CTL_MOD, 8, {EPOLLIN|EPOLLET, {u32=12753536, u64=12753536}}) = 0
epoll_wait(4, {{EPOLLIN, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
gettimeofday({1434554349, 142041}, NULL) = 0
read(8, "*2\r\n$6\r\nSELECT\r\n$1\r\n0\r\n", 16336) = 23
getpeername(8, {sa_family=AF_FILE, NULL}, [2]) = 0
epoll_ctl(4, EPOLL_CTL_DEL, 8, NULL)    = 0
gettimeofday({1434554349, 142145}, NULL) = 0
close(8)                                = 0
epoll_wait(4, {{EPOLLIN, {u32=12753264, u64=12753264}}}, 1024, 30000) = 1
accept(7, 0, NULL)                      = 8
fcntl(8, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(8, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
epoll_ctl(4, EPOLL_CTL_ADD, 8, {EPOLLIN|EPOLLOUT|EPOLLET, {u32=12753536, u64=12753536}}) = 0
accept(7, 0, NULL)                      = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(4, {{EPOLLOUT, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
epoll_ctl(4, EPOLL_CTL_MOD, 8, {EPOLLIN|EPOLLET, {u32=12753536, u64=12753536}}) = 0
epoll_wait(4, {{EPOLLIN, {u32=12753536, u64=12753536}}}, 1024, 30000) = 1
gettimeofday({1434554350, 915098}, NULL) = 0
read(8, "*1\r\n$4\r\nauth\r\n", 16336)  = 14
getpeername(8, {sa_family=AF_FILE, NULL}, [2]) = 0
epoll_ctl(4, EPOLL_CTL_DEL, 8, NULL)    = 0
gettimeofday({1434554350, 915213}, NULL) = 0
close(8)                                = 0
epoll_wait(4, {}, 1024, 30000)          = 0
epoll_wait(4, {}, 1024, 30000)          = 0
epoll_wait(4, {}, 1024, 30000)          = 0

**Comment by lscgzwd** [comment]
I can connect to redis server directly, but can not use twemproxy as a pool to connect to redis server, it  show me : server closed the connection

**Comment by lscgzwd** [comment]
Sorry, I think i have made a mistake for conf file, resolved .

**Comment by Skycheng168** [comment]
I also encountered this problem.

**Comment by Rishi247** [comment]
@lscgzwd Can you please mention the mistake in the conf file.I too am facing the same issue and am not able to find out the solution for this.

**Comment by lscgzwd** [comment]
@Rishi247 It's a long time ago, I forgot it. sorry

**Comment by frogred8** [comment]
In my case, twemproxy machine couldn't reach redis server.
You'd better check redis address and test a redis connection from twemproxy machine using telnet.
