### ISSUE TITLE
Issue with socket permissions

### ISSUE THREAD

**Issue by dbers** [twitter/twemproxy#382]
We had a working twemproxy with about 9 containers configured.  I added a group of read/write clusters and a few of the permissions on the new and existing sockets got messed up.

After going through all the logs and error reporting and trying to figure it out i just re-arranged the entries and everything started to work.  But i can not figure out why this would of made a difference.  Additional there are no errors on why the socket permissions are wrong.  We also checked character encoding, hidden characters, ext.

We are using version 0.4.0
Below are  the sockets (good and bad) and the configs (good and bad).  Any insight into why this is happening would be useful.  I have another system that is also having these issues but they have over 31 containers defined and simply re-arranging them isn't working.

Bad sockets:
============
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9500.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9501.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9502.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9503.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9504.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9505.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9506.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9507.sock
sr-S--Sr-T 1 apache apache 0 Jun 29 15:31 9508.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9510.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9511.sock
sr-S--Sr-T 1 apache apache 0 Jun 29 15:31 9512.sock
sr-x--x-wx 1 apache apache 0 Jun 29 15:31 9513.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9514.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9515.sock

Good sockets:
=============
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9500.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9501.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9502.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9503.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9504.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9505.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9506.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9507.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9508.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9510.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9511.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9512.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9513.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9514.sock
srwxrwxrwx 1 apache apache 0 Jun 29 15:38 9515.sock

Bad config
==========

group1:
  listen:  /mnt/9500.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:16855:1 REDIS_HOST_USERS

group2:
  listen: /mnt/9501.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:12786:1 REDIS_HOST_BROADCASTS

group3:
  listen: /mnt/9502.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:19473:1 REDIS_HOST_ONLINE_USERS

group4:
  listen: /mnt/9503.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:17674:1 REDIS_HOST_SESSIONS

group5:
  listen: /mnt/9504.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:19861:1 REDIS_HOST_TAGS

group6:
  listen: /mnt/9505.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:12639:1 REDIS_HOST_CHAT

group7:
  listen: /mnt/9506.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:12639:1 REDIS_HOST_TRENDING

group8:
  listen: /mnt/9507.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:11749:1 REDIS_NOTIFICATIONS

group9:
  listen: /mnt/9508.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_HOST_CHAT_LOGS

group10:
  listen: /mnt/9510.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 1
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:18754:1 REDIS_HOST_ONLINE_USERS2

group11:
  listen: /mnt/9511.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  servers:
   - ************************************.garantiadata.com:19473:1 REDIS_HOST_ONLINE_USERS

group12:
  listen: /mnt/9512.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  server_retry_timeout: 5000
  timeout: 500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_WRITE_CLUSTER_1

group13:
  listen: /mnt/9513.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  server_retry_timeout: 5000
  timeout: 500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_WRITE_CLUSTER_2

group14:
  listen: /mnt/9514.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  server_failure_limit: 2
  server_connections: 40
  redis: true
  server_retry_timeout: 5000
  timeout: 1500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_READ_CLUSTER_1_N1
   - ************************************.cache.amazonaws.com:6379:1 REDIS_READ_CLUSTER_1_N2

group15:
  listen: /mnt/9515.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  server_failure_limit: 2
  server_connections: 40
  redis: true
  server_retry_timeout: 5000
  timeout: 1500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_READ_CLUSTER_2_N1
   - ************************************.cache.amazonaws.com:6379:1 REDIS_READ_CLUSTER_2_N2

Good config
============

group1:
  listen:  /mnt/9500.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:16855:1 REDIS_HOST_USERS

group2:
  listen: /mnt/9501.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:12786:1 REDIS_HOST_BROADCASTS

group3:
  listen: /mnt/9502.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:19473:1 REDIS_HOST_ONLINE_USERS

group4:
  listen: /mnt/9503.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:17674:1 REDIS_HOST_SESSIONS

group5:
  listen: /mnt/9504.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:19861:1 REDIS_HOST_TAGS

group6:
  listen: /mnt/9505.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:12639:1 REDIS_HOST_CHAT

group7:
  listen: /mnt/9506.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:12639:1 REDIS_HOST_TRENDING

group9:
  listen: /mnt/9508.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_HOST_CHAT_LOGS

group8:
  listen: /mnt/9507.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:11749:1 REDIS_NOTIFICATIONS

group10:
  listen: /mnt/9510.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 1
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  timeout: 500
  servers:
   - ************************************.garantiadata.com:18754:1 REDIS_HOST_ONLINE_USERS2

group11:
  listen: /mnt/9511.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  redis_auth: *******
  server_retry_timeout: 2000
  servers:
   - ************************************.garantiadata.com:19473:1 REDIS_HOST_ONLINE_USERS

group13:
  listen: /mnt/9513.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  server_retry_timeout: 5000
  timeout: 500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_WRITE_CLUSTER_2

group14:
  listen: /mnt/9514.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  server_failure_limit: 2
  server_connections: 40
  redis: true
  server_retry_timeout: 5000
  timeout: 1500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_READ_CLUSTER_1_N2

group15:
  listen: /mnt/9515.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  server_failure_limit: 2
  server_connections: 40
  redis: true
  server_retry_timeout: 5000
  timeout: 1500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_READ_CLUSTER_2_N2

group12:
  listen: /mnt/9512.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  server_connections: 10
  redis: true
  server_retry_timeout: 5000
  timeout: 500
  servers:
   - ************************************.cache.amazonaws.com:6379:1 REDIS_WRITE_CLUSTER_1

**Comment by manjuraj** [comment]
Not sure I understand the issue. Could you elaborate?. What output do you see when you run twemproxy with verbose logging?

**Comment by charsyam** [comment]
what is different between bad config and good config?

**Comment by dbers** [comment]
With verbose set to 11 I am not getting any output that is different then when it works.

The issue is mainly the permissions are wrong on the socket files (seems to be no write permission) so clients can't connect.

A work around i have right now for my larger config is simply issuing chmod 777 on a delay and it appears to fix the socket permissions. Even though it works i'm a little concerned why those 3 are having issues with out any config syntax issues, logging errors, or any other indication that there is something specifically wrong with those configs. 

This morning i added 16 new redis containers to the nutcracker config and all of them start up correctly.  So i'm thinking its an issue with those specific configs or the redis server i'm connecting to.  But the chmod fixes the issue after the socket is created so a little loss on what the issue could be.

For example: `group13` has issues.  But it it  was made by copping `group12` 's config. However `group14` and `group15` were done the same way but only `group13` has issues. 

I did notice when i manually changed the permissions on 20 ec2 instances about 3 servers had random sockets that didn't change there permissions.  Its possible this is an OS issue, but I am using the latest AMI from amazon and haven't seen any logs that would indicated an issue.  When chmod fails it doesn't throw an error.  It just doesn't change the permissions.  But after a few repeats of the command they are all good.

I'm going to try version  0.4.1 on a new server and see if i explicitly set the permissions and owner if that fixes the issues.  But if that doesn't work i'm out of ideas.

**Comment by dbers** [comment]
I upgraded to version 0.4.1 and if i set the socket permission to 777 in the config it seems to work.

But that still doesn't explain why those 3 are having issues.

**Comment by manjuraj** [comment]
some of the socks have `sr-S--Sr-T 1 apache apache 0 Jun 29 15:31 9508.sock` and others have `sr-x--x-wx 1 apache apache 0 Jun 29 15:31 9513.sock` and finally most of them have `srwxrwxrwx 1 apache apache 0 Jun 29 15:31 9504.sock`.

Pretty confident that you have a background process that is rewriting permissions of these files.

one way to check this is when you start the twemproxy, what are the permissions of these sock files. If over time you see them chaining, then I'm pretty confident that a background process/daemon is rewriting permissions

**Comment by dbers** [comment]
It seems to happen right after starting.

But i'll put a watch on the sockets and see if its ever the correct permission at any time before it changes.

**Comment by manjuraj** [comment]
on your test cluster -- delete all the sock files and then restart twemproxy. What's the behavior for this usecase?

**Comment by dbers** [comment]
The same behavior.  Its always the same sockets with the issue.  Even if i shut down twemproxy, clear out all sockets from directory and then start twemproxy

Our servers rototate every few hours (shut down and reboot new one) and its always same issue.  Which is why i'm thinking there is something with the config.  Even though i've verified it a few times.

And as i mentioned re-arranging the order of tem configs fixes it for the boxes

**Comment by manjuraj** [comment]
specify socket permissions explicitly in the listen directive. See: https://github.com/twitter/twemproxy/pull/311

**Comment by manjuraj** [comment]
@dbers did the socket permission directive fix it?

**Comment by dbers** [comment]
Yes, So far using the permissions directive is working correctly.  

Thanks
Dan

**Comment by rockysoar** [comment]
1448     if (value->data[0] == '/') {
1449         uint8_t *q, *start, *perm;
1450         uint32_t permlen;
1451     
1452     
1453         /* parse "socket_path permissions" from the end */
1454         p = value->data + value->len -1;
1455         start = value->data;
1456         q = nc_strrchr(p, start, ' ');
1457         if (q == NULL) {
1458             /* no permissions field, so use defaults */
1459             name = value->data;
1460             namelen = value->len;
1461         } else {
1462             perm = q + 1;
1463             permlen = (uint32_t)(p - perm + 1);                                                                                                                                                                                
1464 
1465             p = q - 1;
1466             name = start;
1467             namelen = (uint32_t)(p - start + 1);
1468     
1469             errno = 0;
1470             field->perm = (mode_t)strtol((char *)perm, NULL, 8);

reading the source, socket permissions here is parsed from: "socket_path permissions". A space ' ' is beginning of permissions.

But if let permissions empty: "socket_path", the default permissions SHOULD BE inherited from socket's directory(Linux OS specified).

**Comment by TysonAndre** [comment]
This was fixed in 0.5.0-RC1
