### ISSUE TITLE
code that do not understand

### ISSUE THREAD

**Issue by deep011** [twitter/twemproxy#383]
hi, @manjuraj 
i find you add the below code in function core_core():

if (conn->owner == NULL) 
{        
	log_warn("conn is already unrefed!");        
	return NC_OK;    
}

and i can not understand those codes work for what, can you solve question?

**Comment by charsyam** [comment]
@deep011 refer that commit :) https://github.com/twitter/twemproxy/commit/cfbc0bbf653e5f32f4f0ae84cd90cd1a79a88f79

**Comment by deep011** [comment]
@charsyam thank you for quick reply, i'm surprise about this.
