### ISSUE TITLE
about  redis_auth

### ISSUE THREAD

**Issue by peterpaule** [twitter/twemproxy#384]
when i use twemproxy as  redis proxy,  my data is huge , so  i use  ten redis servers, and every redis server has its uniq  passwd, so I can't use redis_auth config;  help

**Comment by charsyam** [comment]
could you change your redis pass as same?

**Comment by peterpaule** [comment]
I can't;  i think maybe every redis server has there own passwd is proper;  Is that so?

**Comment by charsyam** [comment]
@peterpaule Do your servers are open in public network?
or just in private your network?

is it hard to control if every redis server have different passwd?

you want to use twemproxy to control redis cluster.
If so, I think it is better to make them to use same passwd. :)

**Comment by manjuraj** [comment]
All redid server in a given server pool must have the same password. This is the only use case we support
