### ISSUE TITLE
New Ganglia module

### ISSUE THREAD

**Issue by tony-ten** [twitter/twemproxy#385]
My twemproxy module was just merged onto the official Ganglia user-contributed Gmond Python DSO metric modules repository. The module graphs all pool and server stats given by nutcracker. 

https://github.com/ganglia/gmond_python_modules/tree/master/twemproxy

**Comment by manjuraj** [comment]
sweet! 
updated readme -- https://github.com/twitter/twemproxy/commit/29e13cc04dfdab83a5dc118c2076a160a04a58f4
