### ISSUE TITLE
Is the redis.md out of date after 0.4.0?

### ISSUE THREAD

**Issue by Shanicky** [twitter/twemproxy#392]
I found this line in `notes/redis.md`

```
|      SCAN         |    No      | SCAN cursor [MATCH pattern] [COUNT count]             
```

but the ChangeLog says in version 0.4.0

```
 many new commands supported: LEX, PFADD, PFMERGE, SORT, PING, QUIT, SCAN... (mattrobenolt, areina, idning)
```

So is the `notes/redis.md` out of date? 
And where can i figure out all of the unsupported Redis commnads ?

**Comment by charsyam** [comment]
@Shanicky scan is unsupported command.

**Comment by Shanicky** [comment]
But the changelog says `scan` is supported, so is the changelog wrong?

**Comment by manjuraj** [comment]
changelog is wrong
