### ISSUE TITLE
Reg:Dalli Client

### ISSUE THREAD

**Issue by priya23** [twitter/twemproxy#394]
I have pushed the binary memcache branch still while connection Dalli is throughing following error
Dalli::RingError: No server available
	from /Users/user/.rvm/gems/ruby-2.1.5@rails3/gems/dalli-2.7.0/lib/dalli/ring.rb:45:in `server_for_key'
	from /Users/user/.rvm/gems/ruby-2.1.5@rails3/gems/dalli-2.7.0/lib/dalli/client.rb:322:in `perform'
	from /Users/user/.rvm/gems/ruby-2.1.5@rails3/gems/dalli-2.7.0/lib/dalli/client.rb:103:in `set'
	from (irb):6
	from /Users/user/.rvm/gems/ruby-2.1.5@rails3/gems/railties-3.2.18/lib/rails/commands/console.rb:47:in `start'
	from /Users/user/.rvm/gems/ruby-2.1.5@rails3/gems/railties-3.2.18/lib/rails/commands/console.rb:8:in `start'
	from /Users/user/.rvm/gems/ruby-2.1.5@rails3/gems/railties-3.2.18/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

Regards,
Priyanka

**Comment by manjuraj** [comment]
no idea what the issue is
