### ISSUE TITLE
twemproxy issue

### ISSUE THREAD

**Issue by brijesh27** [twitter/twemproxy#413]
While connecting from phpredis to redis server its working fine but when we connect to redis through twemproxy  throwing below errors : 

Fatal error: Uncaught exception 'RedisException' with message 'read error on connection'
cacheRedis->get('667663b57db1d84...')

**Comment by brijesh27** [comment]
Guys, what does forward_error means in twem proxy  and what are the possible causes for it

**Comment by charsyam** [comment]
@brijesh27 hi. could you give me more information?
twemproxy error logs

**Comment by brijesh27** [comment]
i am testing nutcracker with nutcracker-web so not getting any logs, do we have any file where we can define log/error logs with using nutcracker-web

**Comment by brijesh27** [comment]
Server Timedout on twemproxy server showing  307 , 
my I am using nutcracker-web 
my  nutcracker.yml config : 
listen: serverip:22022
  hash: fnv1a_64
  hash_tag: "{}"
  distribution: ketama
  auto_eject_hosts: false
  timeout: 400
  redis: true
  servers:
   - server1: 6379

Few issues i am facing : 
1.   client errors are increased. 
2.   Client EOF 	
3.   Forward Errors

Please let me know how to fix it. 

and now we are getting read exception when trying to connect from client to redis using twemproxy

**Comment by charsyam** [comment]
@brijesh27 Hi :)
What is your redis version and php version also?

**Comment by brijesh27** [comment]
redis 3.0.3  and php version 5.3

**Comment by brijesh27** [comment]
the same thing i am facing as mentioned here "https://github.com/twitter/twemproxy/issues/230"  but this was for memcache and we have the same  for redis.

**Comment by charsyam** [comment]
@brijesh27 How long is your key?

could you show real key?

**Comment by brijesh27** [comment]
We are using 3 redis servers and key ttl is 900 ,
total no of Client Connections is 800 on twemproxy , defined 13G (on redis box total ram 16GB)  for redis and some time it utilizes more than 15G. 

Redis conf is like below : 

daemonize yes
pidfile /var/run/redis_6379.pid
port 6379
tcp-backlog 128
bind 10.20.30.10
timeout 0
tcp-keepalive 0
loglevel verbose
logfile /var/log/redis/redis.log
databases 16
maxclients 9000
maxmemory 13958643712
maxmemory-policy volatile-lru

**Comment by brijesh27** [comment]
i am using bydefault mbuf size i.e. 16K ,  and i have RAM 16GB 
getting below errors in nutcracker logs : 

nc_request.c:416 eof c 446 discarding incomplete req 287080635 len 861024
 nc_request.c:416 eof c 129 discarding incomplete req 426208047 len 50184

**Comment by brijesh27** [comment]
Hi ,
Getting below errors : 
PHP Fatal error:  Uncaught exception 'RedisException' with message 'read error on connection'
now i have 5 redis instances but still getting the same exception

**Comment by charsyam** [comment]
@brijesh27 Do you use "quit" command(like this redis->close() )?

**Comment by charsyam** [comment]
@brijesh27 Do you use phpredis version <= 2.2.7?

**Comment by charsyam** [comment]
@brijesh27 I just think this is related with https://github.com/phpredis/phpredis/commit/d701d02f9c9c58401543560f666f44b5d413a5a7

**Comment by brijesh27** [comment]
yes we are using php redis-2.2.7

**Comment by brijesh27** [comment]
$this->redisObj->pconnect($server['host'], $server['port'], 2);
 we are using singleton design pattern 
but not closing the connection

**Comment by manjuraj** [comment]
@brijesh27 -- you are basically sending commands that is not supported by twemproxy. It is really easy to debug this. 

Step 1) Build a twemproxy binary with --enable-debug=full (https://github.com/twitter/twemproxy/#build)
Step 2) Run this twemproxy, with -v 8 (-v is the logging level)
Step 3) Look at the logs and see which command is being sent
Step 4) See if the command that you are sending is one of the supported commands

Closing this issue; reopen if you still can't figure this out

**Comment by brijesh27** [comment]
@manjuraj ,  client is using get and set command in through twemproxy.

**Comment by abhishekptrt** [comment]
@manjuraj : Please explain  why "read error on connection" comes ? Is it part of redis server configuration or phpredis client part .. which direction we should think ?

**Comment by brijesh27** [comment]
@manjuraj , 
we are getting below error on one of our redis :  


Error writing to client: Broken pipe
Error writing to client: Broken pipe
- Error writing to client: Broken pipe
- Error writing to client: Connection reset by peer
- Error writing to client: Broken pipe
- Error writing to client: Connection reset by peer
- Error writing to client: Connection reset by peer

what are these errors

**Comment by manjuraj** [comment]
@brijesh27 and @abhishekptrt -- did you run the steps: https://github.com/twitter/twemproxy/issues/413#issuecomment-143807568

what did you see in the "verbose" logs of twemproxy

**Comment by brijesh27** [comment]
getting this in nutcracker log : 
[2015-09-29 13:15:21.190] nc.c:187 nutcracker-0.4.1 built for Linux 2.6.32-573.3.1.el6.x86_64 x86_64 started on pid 32644
[2015-09-29 13:15:21.190] nc.c:192 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one
[2015-09-29 14:10:02.237] nc_response.c:118 s 22 active 0 is done
[2015-09-29 14:10:02.239] nc_response.c:118 s 11 active 0 is done
[2015-09-29 14:10:02.239] nc_response.c:118 s 23 active 0 is done
[2015-09-29 14:10:27.973] nc_response.c:118 s 24 active 0 is done

**Comment by manjuraj** [comment]
you have to build the nutcracker with --enable-debug=full for this logging to be useful

**Comment by brijesh27** [comment]
i have did the same and tried with v8 ,v 11both 
nutcracker -c /pathofnutcracker/nutcracker.yml -v 8 -o /var/log/nutcracker/nutcracker.log -m 1024 -d

**Comment by brijesh27** [comment]
@manjuraj , i amd getting below in nutcracker logs : 

[2015-09-30 17:54:24.472] nc_connection.c:423 sendv on sd 75 failed: Broken pipe

**Comment by manjuraj** [comment]
you haven't compiled nutcracker in debug mode. Run this, and reproduce the logs, paste it here:

$ CFLAGS="-ggdb3 -O0" ./configure --enable-debug=full
$ make
$ sudo make install

Also broken pipe is EPIPE -- it happens if client or server closes the connection before receiving all data

**Comment by brijesh27** [comment]
@manjuraj ,
I am getting below errors on my redis instances : 

7366:M 06 Oct 14:42:47.405 - Error writing to client: Connection reset by peer
7366:M 06 Oct 14:42:47.405 - Error writing to client: Connection reset by peer
7366:M 06 Oct 14:42:47.487 - Error writing to client: Broken pipe
2051:M 06 Oct 15:46:54.463 - Error writing to client: Broken pipe
2051:M 06 Oct 15:46:54.464 - Error writing to client: Broken pipe

what are these errors related to ,  due to this my webservers throwing "read error on connection"

**Comment by manjuraj** [comment]
Broken pipe means that either your client closed the connection before nutcracker had a chance to write to it or it closed by sending TCP RST instead of TCP FIN

**Comment by brijesh27** [comment]
Thanks manjuraj,
so i need to increase the timeout to avoid such conditions
