### ISSUE TITLE
Redis closing connection issue 

### ISSUE THREAD

**Issue by Ragazzo** [twitter/twemproxy#417]
This issue is a follow up for #386 , while descovering logs we found that when closing connect to Redis twemproxy marks this operation as error, is this a correct behaviour or we missed anything? 

```
[2015-10-01 11:56:32.773] nc_epoll.c:254 epoll 0001 triggered on conn 0x24d5740
[2015-10-01 11:56:32.773] nc_core.c:324 event 00FF on c 654
[2015-10-01 11:56:32.773] nc_util.c:228 malloc(32) at 0x24d66b0 @ nc_array.c:29
[2015-10-01 11:56:32.773] nc_util.c:228 malloc(16) at 0x24d66e0 @ nc_array.c:34
[2015-10-01 11:56:32.773] nc_message.c:319 get msg 0x24d64f0 id 923356 request 1 owner sd 654
[2015-10-01 11:56:32.773] nc_mbuf.c:99 get mbuf 0x24ec1d0
[2015-10-01 11:56:32.773] nc_mbuf.c:182 insert mbuf 0x24ec1d0 len 0
[2015-10-01 11:56:32.773] nc_connection.c:362 recv on sd 654 6 of 976
[2015-10-01 11:56:32.773] nc_redis.c:1643 parsed bad req 923356 res 1 type 0 state 0
00000000  51 55 49 54 0d 0a                                  |QUIT..|
[2015-10-01 11:56:32.773] nc_core.c:198 recv on c 654 failed: Invalid argument
[2015-10-01 11:56:32.773] nc_core.c:237 close c 654 '127.0.0.1:47266' on event 00FF eof 0 done 0 rb 28175 sb 50818: Invalid argument
[2015-10-01 11:56:32.773] nc_stats.c:1033 metric 'client_connections' in pool 1
[2015-10-01 11:56:32.773] nc_stats.c:1065 decr field 'client_connections' to -1
[2015-10-01 11:56:32.773] nc_stats.c:1033 metric 'client_err' in pool 1
[2015-10-01 11:56:32.773] nc_stats.c:1050 incr field 'client_err' to 7
[2015-10-01 11:56:32.773] nc_client.c:147 close c 654 discarding pending req 923356 len 6 type 0
[2015-10-01 11:56:32.773] nc_message.c:370 put msg 0x24d64f0 id 923356
[2015-10-01 11:56:32.773] nc_mbuf.c:191 remove mbuf 0x24ec1d0 len 6
[2015-10-01 11:56:32.773] nc_mbuf.c:121 put mbuf 0x24ec1d0 len 6
[2015-10-01 11:56:32.773] nc_util.c:274 free(0x24d66e0) @ nc_array.c:77
[2015-10-01 11:56:32.773] nc_util.c:274 free(0x24d66b0) @ nc_array.c:51
```

Could this be a reason because we close connection on Redis (twemproxy) with `client.close()` thus it triggers `QUIT` command that is send to `twemproxy` and `twemproxy` send it to `Redis` and this situation occurs? 

//cc @manjuraj

**Comment by charsyam** [comment]
@Ragazzo I have a question do you use php? I think it is related with this :)
https://github.com/phpredis/phpredis/commit/d701d02f9c9c58401543560f666f44b5d413a5a7
phpredis 2.2.7 has a problem send quit message as inline command.
twemproxy can't process inline command.

**Comment by Ragazzo** [comment]
@charsyam i think you are right, dont they have plans to fixing it by undo those changes?

**Comment by charsyam** [comment]
@Ragazzo They remove that code. so current master branch maybe ok. 
But I'm not sure that they don't use inline command at other code.

**Comment by Ragazzo** [comment]
what other code you are referring in particular?

**Comment by manjuraj** [comment]
@Ragazzo we do handle QUIT command, but not the format the you mention. We handle this: `*1\r\n$4\r\nquit\r\n` and NOT this `quit\r\n`
Details
- https://github.com/twitter/twemproxy/blob/master/src/proto/nc_redis.c#L668-L672
- https://github.com/twitter/twemproxy/blob/master/src/proto/nc_redis.c#L350-L373 (_Nutcracker only supports the Redis unified protocol for requests_)

**Comment by Ragazzo** [comment]
@manjuraj i see, looks like issue is in the `phpredis` and how it was sending `QUIT` command as mentioned @charsyam , we recompiled it with those lines removed like in above `2.2.7` and it was working fine on test-case. Can you also clarify the use-case: if we use `preconnect` and `twemproxy` use persistent connections, will it re-open connection once it closed by `Redis` on its side as in example above? or persistent connections are not re-opened in `twemproxy`?

**Comment by manjuraj** [comment]
> Can you also clarify the use-case: if we use preconnect and twemproxy use persistent connections, will it re-open connection once it closed by Redis on its side as in example above? or persistent connections are not re-opened in twemproxy?

it will reopen the connection

**Comment by charsyam** [comment]
@Ragazzo I looked up current phpredis code(specially library.c in master branch), maybe they already remove all code that send 'inline command"  in master branch

**Comment by Ragazzo** [comment]
@manjuraj thanks

@charsyam ok, thank you, we recompiled it with that commit removing those lines, but later will recompile from master

**Comment by Ragazzo** [comment]
@manjuraj can you clarify in your [recommendation](https://github.com/twitter/twemproxy/blob/master/notes/recommendation.md) there is a timeout for `400` msec as i see, am i correct? 
In logs with debug full we see timings like `req 591882 done on c 24 req_time 0.290 msec` is this 290 msec, or it is 0.290 of one msec? 
Also is 400 enough for server with 96 Gb RAM, 12 cores with 3.5 GHz, just as a brief thought should this be enough or not,  this server holds 12 redis servers and 6 twemproxies (for more availability and since redis can work only on one core)

**Comment by manjuraj** [comment]
0.290 msec; 400 msec should be good; though you should run some perf before arriving at any numbers

**Comment by Ragazzo** [comment]
@manjuraj can you clarify can `twemproxy` use unix domain sockets while connecting and working with `Redis` since in `Redis` docs it is mentioned that more throughput can be gained by using them?

**Comment by manjuraj** [comment]
you can use unix domain sockets as part of the "listen" directive or as part of server directive

**Comment by Ragazzo** [comment]
can you please elaborate where is this option in docs or maybe give brief example on this one?

**Comment by manjuraj** [comment]
+ listen directive -- https://github.com/twitter/twemproxy/blob/master/conf/nutcracker.yml#L61
+ servers -- https://github.com/twitter/twemproxy/blob/master/src/nc_conf.c#L1556

**Comment by Ragazzo** [comment]
thank you, i will close this issue, since we decided for now to build hiearchy of twemproxies to solve our problem. If anything new will show up i will reopen this. Also is there any forum or something where we can ask such questions or it is fine to ask them here on github?

**Comment by manjuraj** [comment]
github is good. most of the answers for twemproxy questions can be found in recommendation.md 
few more resources
+ https://speakerdeck.com/justinmares/twemproxy
+ http://redisconference.com/video/running-twemproxy-in-production/

**Comment by Ragazzo** [comment]
thanks

**Comment by Ragazzo** [comment]
@manjuraj one side question, does twemproxy have any handoff ? when i was starting with 6 redis, then shutting one down, got data to 5, then started 6 server, and data was also redistributed to it. Are you making rehash for [consistent hashing](https://en.wikipedia.org/wiki/Consistent_hashing) K/n keys like said, or there is any handoff like hinted that comes in play when node comes back online? Just curiosity to not to debug / search all `twemproxy` code ;)
