### ISSUE TITLE
Is function 'memcache_copy_bulk()' in nc_memcache.c safe

### ISSUE THREAD

**Issue by helifu** [twitter/twemproxy#436]
the format of the response for get/gets is:
"VALUE key1 0 len1\r\nval1\r\nVALUE key2 0 len2\r\nval2\r\nEND\r\n"

is it safe while you are eating 'VALUE key 0'? (line 1450)
maybe string 'VALUE key 0' is fragmented into two mbuf?

```
for (i = 0; i < 3; i++) {                 /*  eat 'VALUE key 0 '  */
    for (; *p != ' ';) {
        p++;
    }
    p++;
}
```

**Comment by TysonAndre** [comment]
It should be safe. **twemproxy allocates different msg structures for each `VALUE key1 0 len1\r\nval1\r\n` section in responses and each msg has a separate list of 1 or more mbufs** 

The `VALUE key 0` starts at the start of an mbuf.

The maximum length of a memcache key is 250
```
#define MEMCACHE_MAX_KEY_LENGTH 250
``` 

The minimum mbuf size is 512 bytes. twemproxy will only split up an mbuf for a given message once that maximum is reached

```
// src/nc.c
#define MBUF_MIN_SIZE   512
#define MBUF_MAX_SIZE   16777216
#define MBUF_SIZE       16384
```

**Comment by TysonAndre** [comment]
Hypothetically, an extremely long number might overflow that mbuf, but that wouldn't be sent by a valid memcache server.
