### ISSUE TITLE
How to dynamically add a redis instance and migrate data?

### ISSUE THREAD

**Issue by TrumanDu** [twitter/twemproxy#453]
@idning 
How to dynamically add a redis instance and migrate data?
What I mean is extended.looking forward to your reply.

**Comment by charsyam** [comment]
@TrumanDu currently there is no way to add a redis instance dynamically. 
even though you add new redis instance 
(for example: running new twemproxy with new port and connecting it.)
It is hard to migrate some data that will be included new server

**Comment by TrumanDu** [comment]
@charsyam thanks,I also just think this method.but do not know how more companies are dealing with this issue.

**Comment by charsyam** [comment]
@TrumanDu In my case, I use zookeeper for dynamic configuration.
so If I add new server, api server can connect new redis or new twemproxy 서버.

**Comment by TrumanDu** [comment]
@charsyam Can you tell me about the detailed structure it?

**Comment by charsyam** [comment]
@TrumanDu 
similar this : http://d2.naver.com/content/images/2015/06/helloworld-294797-4.png
