### ISSUE TITLE
redis_db and redis_auth

### ISSUE THREAD

**Issue by limbo127** [twitter/twemproxy#457]
hello, 
it seems select is done before auth command, 
so when we are using both redis_db ( 2 for example ) and redis_auth , it does not work.
Select must be done after auth command

Regards, 
Nicolas

**Comment by charsyam** [comment]
@limbo127 hi.
Could you try this version?
https://github.com/charsyam/twemproxy/tree/feature/refactoring_add_auth_to_post_connected
I patched this :)

**Comment by limbo127** [comment]
hello,
this patch seems to be ok,
thanks for this quicky version
Regards,
Nicolas

2016-03-09 18:01 GMT+01:00 charsyam <notifications@github.com>:
