### ISSUE TITLE
 0.4.1 release support USR1 signal?

### ISSUE THREAD

**Issue by JeffXue** [twitter/twemproxy#467]
I am using 0.4.1 release version. But when i change my config file and send USR1 signal, it did't wok?
If i kill the process and restart it ,if will be fine. That why?

**Comment by TysonAndre** [comment]
The answer seems to be: no, it doesn't.

Related to https://github.com/twitter/twemproxy/pull/321 , which was a PR **proposing to support config reload that was never merged.** The concept seems convenient (I haven't looked at the implementation and I am not a maintainer) but any implementation may be hard to maintain the code for (e.g. avoid connection/memory leaks/client connections that stay open, edge cases, etc.)

The current behavior seems to be a deliberate no-op, the same as when the signal handler was first introduced. See src/nc_signal.c
