### ISSUE TITLE
why nutcracker occput port 26379. conflict with redis sentinel

### ISSUE THREAD

**Issue by JeffXue** [twitter/twemproxy#468]
![image](https://cloud.githubusercontent.com/assets/3280855/14780067/a53a6db2-0b0d-11e6-98ba-6678f44a9e5c.png)

**Comment by TysonAndre** [comment]
It's probably because you or whoever set up nutcracker configured it to listen on port 26379 in nutcracker.yml.

Closing this due to issue age - this is inactionable without the nutcracker.yml file contents and twemproxy version.
