### ISSUE TITLE
Issue - One server not seeing any requests.

### ISSUE THREAD

**Issue by jennyfountain** [twitter/twemproxy#473]
Help!  We just installed this into production today and seeing some issues

Here is the stats report:
  "gamma": {
        "1.2.3.4": {
            "in_queue": 0, 
            "in_queue_bytes": 0, 
            "out_queue": 0, 
            "out_queue_bytes": 0, 
            "request_bytes": 0, 
            "requests": 0, 
            "response_bytes": 0, 
            "responses": 0, 
            "server_connections": 1, 
            "server_ejected_at": 0, 
            "server_eof": 0, 
            "server_err": 0, 
            "server_timedout": 0
        }, 
        "5.6.7.8": {
            "in_queue": 1, 
            "in_queue_bytes": 44, 
            "out_queue": 0, 
            "out_queue_bytes": 0, 
            "request_bytes": 33207423, 
            "requests": 235852, 
            "response_bytes": 78380242, 
            "responses": 235762, 
            "server_connections": 1, 
            "server_ejected_at": 0, 
            "server_eof": 0, 
            "server_err": 0, 
            "server_timedout": 2
        }, 
        "client_connections": 46, 
        "client_eof": 604, 
        "client_err": 88, 
        "forward_error": 89, 
        "fragments": 0, 
        "server_ejects": 0
    },

Config:
gamma:
  listen: 127.0.0.1:22224
  auto_eject_hosts: true
  distribution: ketama
  hash: crc32
  backlog: 1024
  preconnect: true
  server_failure_limit: 3
  server_retry_timeout: 30000
  servers:
   - 1.2.3.4:11211:1
   - 5.6.7.8:11211:1
  timeout: 400

Thanks!

CentOS 6.7
nutcracker-0.4.1

**Comment by charsyam** [comment]
how many requests did you send?

**Comment by jennyfountain** [comment]
i do not have that information available right now (not at my desk). But will get that info. However, it is a busy server and each request does a memcache lookup.

**Comment by jennyfountain** [comment]
The server is reporting about 5,390 rpm.

 "1.2.3.4": {
            "in_queue": 0, 
            "in_queue_bytes": 0, 
            "out_queue": 0, 
            "out_queue_bytes": 0, 
            "request_bytes": 0, 
            "requests": 0, 
            "response_bytes": 0, 
            "responses": 0, 
            "server_connections": 1, 
            "server_ejected_at": 0, 
            "server_eof": 0, 
            "server_err": 0, 
            "server_timedout": 0
        }, 
        "5.6.7.8": {
            "in_queue": 1, 
            "in_queue_bytes": 25, 
            "out_queue": 0, 
            "out_queue_bytes": 0, 
            "request_bytes": 1700815899, 
            "requests": 11790364, 
            "response_bytes": 4275045540, 
            "responses": 11787057, 
            "server_connections": 1, 
            "server_ejected_at": 0, 
            "server_eof": 0, 
            "server_err": 0, 
            "server_timedout": 95
        }, 
        "client_connections": 38, 
        "client_eof": 32828, 
        "client_err": 3274, 
        "forward_error": 3306, 
        "fragments": 0, 
        "server_ejects": 0

**Comment by jennyfountain** [comment]
We determined that it was the hash we were using! Sorry.

**Comment by charsyam** [comment]
@jennyfountain good.

**Comment by jennyfountain** [comment]
This was our issue https://github.com/twitter/twemproxy/issues/402
