### ISSUE TITLE
python-memcached warning is now out of date

### ISSUE THREAD

**Issue by thenewguy** [twitter/twemproxy#475]
I have been reading about twemproxy for a python environment.  I noticed your warning about [python-memcached](https://github.com/twitter/twemproxy/blob/master/notes/recommendation.md#twemproxy-and-python-memcached) and investigated.  It looks like this is now fixed per https://github.com/linsomniac/python-memcached/commit/81cd83d713738f4d707c404d89f4544d89895943

**Comment by charsyam** [comment]
@thenewguy Yes, It is fixed :)

**Comment by TysonAndre** [comment]
> Yes, It is fixed :)

Closing

**Comment by thenewguy** [comment]
@TysonAndre only have my phone at the moment but I don't think this is fixed per https://github.com/twitter/twemproxy/blob/48e3f39c36d0e6b71c0e0375bfec8588ca34e3b6/notes/recommendation.md#L158

**Comment by TysonAndre** [comment]
Oh. I thought you meant a warning emitted by python, not a docs warning to developers using that library
