### ISSUE TITLE
PHP code error - resultCode=47 - with nutcracker

### ISSUE THREAD

**Issue by jennyfountain** [twitter/twemproxy#478]
We keep seeing timeouts in our code when trying to use twemproxy and getting frustrated as to why.  We are not seeing the same errors going directly to memcache. 

Here is my config:

socket:
  listen: /var/run/nutcracker/memcache.sock
  auto_eject_hosts: true
  distribution: ketama
  hash: one_at_a_time
  backlog: 65536
  preconnect: true
  server_connections: 1
  server_failure_limit: 1
  server_retry_timeout: 600000
  servers:
   - x.x.x.x:11211:1
   - x.x.x.x:11211:1
  timeout: 250

I can send an example of the code if needed.

any help will be greatly appreciated.
-J

**Comment by jennyfountain** [comment]
Anyone else have memcache timeouts using php?

**Comment by charsyam** [comment]
@jennyfountain what kind of command do you use?

**Comment by charsyam** [comment]
@jennyfountain I hope this is helpful http://stackoverflow.com/questions/19681201/memcached-error-in-fuelphph-error-code-47

**Comment by jennyfountain** [comment]
We were using this:

nutcracker -d -c /etc/nutcracker/nutcracker.yml

now using this to troubleshoot more but still seeing issues

nutcracker -o /var/log/nutcracker -d -v 7 -m 512 -c /etc/nutcracker/nutcracker.yml

**Comment by jennyfountain** [comment]
some more info
rpm -qa | grep libmem
libmemcached-devel-1.0.4-1_6.x86_64
libmemcached-1.0.4-1_6.x86_64

PHP 5.3.29 (cli) (built: Aug 27 2014 09:30:10) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies

memcache module - 3.0.8
memcached module - 2.2.0

**Comment by jennyfountain** [comment]
We determined the problem. Our PHP code is set to timeout at 1000 msec and nutcracker was set to 400.  We bumped nutcracker up to 1000 and all is working!

**Comment by charsyam** [comment]
@jennyfountain Good.

**Comment by digitalprecision** [comment]
@jennyfountain "Our PHP code is set to timeout at 1000 msec" are you referring to max_execution_time? I am experiencing timeouts as well, and thought upping nutcracker.yml timeout to 1000 (from 100) might solve the problem. Our current php max_execution_time is 30 seconds, but I can't imagine dropping this down to 1 second?
