### ISSUE TITLE
Is it actively maintained?

### ISSUE THREAD

**Issue by okapies** [twitter/twemproxy#479]
Someone mentioned this great software, but I'm concerned if it is still maintained by authors or not. Does anyone know the roadmap of twemproxy?

**Comment by charsyam** [comment]
@okapies Frankly Speaking, Twmproxy is not maintained.
so. If you want to get some information? It's OK.
but if you want to get new feature, It is hard to get.
But there are some unofficial branches.

**Comment by okapies** [comment]
Thanks for your quick reply. I want to know why there isn't an official community around Twemproxy in spite of its [wide adoption](https://github.com/twitter/twemproxy#companies-using-twemproxy-in-production)? Is there any popular alternatives?

**Comment by andyqzb** [comment]
@okapies The project will add some new feature recently. I was just invited to the maintainers. I will start the work very soon.

**Comment by silviucpp** [comment]
@andyqzb can you please share what exactly will be added ?

Silviu

**Comment by manjuraj** [comment]
@okapies community building takes time and requires volunteers :) 

I would be more than excited and happily endorse anyone who would like to lead the charge towards community building

**Comment by charsyam** [comment]
@manjuraj Could you have any plan to twemproxy community make active?

**Comment by Atompeng** [comment]
@andyqzb Any progress to report? There are several straightforward PRs that would make for a quick (and useful) update.

**Comment by sunny-shu** [comment]
@andyqzb 
hi，andyqzb 。this is great software,but i found no one to handle issue and PR.
do you have  a plan to make it  active, and does this project need a new maintainer.
i am glade to do a favor.

**Comment by TysonAndre** [comment]
I was added as a collaborator yesterday, see https://github.com/twitter/twemproxy/issues/608 - new releases are planned
