### ISSUE TITLE
Core dump in memcache_fragment code

### ISSUE THREAD

**Issue by jgarlow** [twitter/twemproxy#481]
We have had two coredumps in our production environment since May and I'm posting information here to see if anyone else has seen a crash like these.   I've looked through other open and closed core dump issues and don't see any references to "memcache_fragment" in the backtrace so I think (but am in no way sure) that this is something different.  We also have not be able to recreate in our staging environment so I am really unclear what the cause is.  

Still - if you have seen something like this then let me know and make we can work together on a cause.

Here are the core dumps:

May 24th
root@prod-web-18:~# cat /var/log/nutcracker/nutcracker.log
/usr/sbin/nutcracker(nc_stacktrace_fd+0x2a)[0x40f80a]
/usr/sbin/nutcracker(signal_handler+0x49)[0x40d539]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7fab8195c8d0]
/usr/sbin/nutcracker(memcache_fragment+0x109)[0x413329]
/usr/sbin/nutcracker(req_recv_done+0xc0)[0x409630]
/usr/sbin/nutcracker(msg_recv+0x28e)[0x408b7e]
/usr/sbin/nutcracker(core_core+0x81)[0x405851]
/usr/sbin/nutcracker(event_wait+0xe7)[0x419097]
/usr/sbin/nutcracker(core_loop+0x19)[0x405cc9]
/usr/sbin/nutcracker(main+0x5e0)[0x405270]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fab812c4b45]
/usr/sbin/nutcracker[0x405638]
[.......................] signal 11 (SIGSEGV) received, core dumping
July 11
<didn't grab the very start> nc_response.c:118 s 7 active 0 is done
/usr/sbin/nutcracker(nc_stacktrace_fd+0x2a)[0x40f80a]
/usr/sbin/nutcracker(signal_handler+0x49)[0x40d539]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7f28ea92f8d0]
/usr/sbin/nutcracker(mbuf_insert+0xc)[0x409e3c]
/usr/sbin/nutcracker(msg_ensure_mbuf+0x61)[0x4086e1]
/usr/sbin/nutcracker(memcache_fragment+0x11c)[0x41333c]
/usr/sbin/nutcracker(req_recv_done+0xc0)[0x409630]
/usr/sbin/nutcracker(msg_recv+0x28e)[0x408b7e]
/usr/sbin/nutcracker(core_core+0x81)[0x405851]
/usr/sbin/nutcracker(event_wait+0xe7)[0x419097]
/usr/sbin/nutcracker(core_loop+0x19)[0x405cc9]
/usr/sbin/nutcracker(main+0x5e0)[0x405270]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f28ea297b45]
/usr/sbin/nutcracker[0x405638]
[.......................] signal 11 (SIGSEGV) received, core dumping

**Comment by flex1988** [comment]
do you have a core file?

**Comment by TysonAndre** [comment]
Very likely fixed by https://github.com/twitter/twemproxy/pull/595 which will be part of 0.5.0
