### ISSUE TITLE
ubuntu package doesn't run under systemd

### ISSUE THREAD

**Issue by stralytic** [twitter/twemproxy#485]
the systemd service file in the ubuntu packages is incorrect. I had to modify it to below to get it to work on xenial.
- The override file needs a - before its filename to make it optional.
- The ExecStart line was looking for the binary in /usr/bin instead of /usr/sbin

```
[Unit]
Description=nutcracker/twemproxy

[Service]
EnvironmentFile=/etc/default/twemproxy
EnvironmentFile=-/etc/default/twemproxy.override

ExecStart=/usr/sbin/nutcracker $DAEMON_ARGS

[Install]
WantedBy=multi-user.target
```

**Comment by guilhem** [comment]
Hi @stralytic ,

Code for twemproxy packaging is sadly not in this repository, but here: http://bazaar.launchpad.net/~twemproxy/twemproxy/debian/view/head:/twemproxy.service

If you are looking to support packaging you can join _twemproxy_ team on launchpad.

For the moment I added your change here: http://bazaar.launchpad.net/~twemproxy/twemproxy/debian/revision/8

Many thanks
