### ISSUE TITLE
memory leak bug

### ISSUE THREAD

**Issue by deep011** [twitter/twemproxy#487]
Hi, @manjuraj 
We are used many mset commands at a twemproxy, and the twemproxy's memory keep increasing all the time.
I reviewed the twemproxy code carefully and find there are some mbufs were not be recovered in the redis_copy_bulk() function at some point.

And i make a pull request #486  for this bug, please help me check it. Thank you!

**Comment by andyqzb** [comment]
fixed in PR #486
