### ISSUE TITLE
PFCOUNT does not work for multiple keys

### ISSUE THREAD

**Issue by freedom1989** [twitter/twemproxy#495]
I'm using version 0.4.1.
`PFCOUNT` is working for one key, but not working for multiple keys:

``` bash
pfcount key1
> pfcount {user1}-hll1
(integer) 3
> pfcount {user1}-hll2
(integer) 2
> pfcount {user1}-hll1 {user1}-hll2
Error: Server closed the connection
```

is multiple keys for `PFCOUNT` not supported? or do I need to do some extra configuration to enable it?

**Comment by refaelos** [comment]
@freedom1989 do you have a resolution for this?

**Comment by TysonAndre** [comment]
https://github.com/twitter/twemproxy/pull/599/files should fix this

**Comment by TysonAndre** [comment]
```
127.0.0.1:22121> pfadd pfkey a b c
(integer) 1
127.0.0.1:22121> pfadd pfkey1 d e f 
(integer) 1
127.0.0.1:22121> PFCOUNT pfkey pfkey1
(integer) 6
127.0.0.1:22121> pfcount pfkey
(integer) 3
127.0.0.1:22121> pfcount pfkey1
(integer) 3
```

This works with twemproxy with a single backend server. Note that this will be inaccurate for multiple keys, especially with host ejection handling and failover patches planned for 0.6.0 making it harder to reason about whether keys should go to the same backend server
