### ISSUE TITLE
Redis mget with no arguments blocks instead of returning error

### ISSUE THREAD

**Issue by kerrick-lyft** [twitter/twemproxy#500]
When you run `mget` with no arguments against a normal Redis instance, it returns an error:

```
127.0.0.1:6379> mget
(error) ERR wrong number of arguments for 'mget' command
127.0.0.1:6379> 
```

When you run mget without arguments against Twemproxy, however, it blocks forever:

```
redis /var/run/nutcracker/my_redis_cluster.sock> mget
[... control is never returned to the command prompt ...]
```

**Comment by charsyam** [comment]
try this https://github.com/twitter/twemproxy/pull/423/files

**Comment by TysonAndre** [comment]
This should be fixed in https://github.com/twitter/twemproxy/pull/611 - this includes a fix for the same issue https://github.com/twitter/twemproxy/pull/423/files fixed
