### ISSUE TITLE
Please support the server command 'COMMAND' as 'redis-cli' uses it for non-interactive commands

### ISSUE THREAD

**Issue by ArcticSnowman** [twitter/twemproxy#518]
Please support the server command 'COMMAND' as 'redis-cli' uses it for non-interactive commands.

`redis-cli GET <key>`  does not work for twemproxy as redis-cli issues a `COMMAND` command to check that you have a valid command to send. 

This works in interactive mode...

**Comment by TysonAndre** [comment]
https://github.com/twitter/twemproxy/pull/565 supports processing nested multi-bulks (arrays of arrays...) with a hardcoded maximum depth of 4, so it can be used as a pre-requisite to solve this.

With https://github.com/ifwe/twemproxy/pull/38 `COMMAND` is working, e.g. `redis-cli` 5 was aware of the ZMSCORE command from redis 6.2.0+

**Comment by TysonAndre** [comment]
Closed in #599 , should be available in an upcoming 0.5.0 release
