### ISSUE TITLE
Redis SPOP command is not supported with optional argument. 

### ISSUE THREAD

**Issue by rishitoko** [twitter/twemproxy#550]
Hi,
I am facing one issue while using twinproxy in our production environment. 
It does not support Redis SPOP command with the optional argument.

command: 
**SPOP myset 1**
Error: Server closed the connection

Please resolve if possible.

**Comment by charsyam** [comment]
@rishitoko If you don't mind using not official version.
just try my patch. 
https://github.com/charsyam/twemproxy/tree/maintain
I also sent a pr.

**Comment by andygrunwald** [comment]
PR can be found at #551

**Comment by TysonAndre** [comment]
It seems like #551 was merged and will be part of 0.5.0 - file a new issue if any work is remaining
