### ISSUE TITLE
Redis exception : Connection closed randomly

### ISSUE THREAD

**Issue by davidnjuko** [twitter/twemproxy#559]
I'm using twemproxy for redis in a production environment and sometime we have failure happening. 

When a failure occurred I can see in nutcracker logs that there is a lot of messages like this one :

> [2018-05-22 14:11:58.506] nc_response.c:118 s 61 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 60 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 59 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 58 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 57 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 56 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 55 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 54 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 53 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 51 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 49 active 0 is done
> [2018-05-22 14:11:58.506] nc_response.c:118 s 50 active 0 is done

I tried to compile twemproxy with the debug option and message is exactly the same without more informations.

I have 6 instances of nutcracker running on the same server proxying request for many redis servers.
Here is the configuration file I'm using for one of the 6 nutcracker for example on port 6379 

> session:
>   listen: 172.31.16.38:6379
>   client_connections: 10000
>   hash: fnv1a_64
>   distribution: ketama
>   auto_eject_hosts: true
>   redis: true
>   server_retry_timeout: 100
>   preconnect: true
>   server_connections: 500
>   timeout: 10000
>   server_failure_limit: 100
>   servers:
>     - 172.31.25.8:6379:1 session17231258

We tried many solutions, today I'm trying with the auto_eject_host : false to see if there is any change.
But if you already encountered this kind of behaviour I really would like to know where we can improve our system to avoid tis kind of failure

(Redis servers and redis proxy are on reserved EC2 instances m5.2xlarge, using private network)

**Comment by alex-icesoft** [comment]
Any solution here ?

**Comment by TysonAndre** [comment]
This may be a symptom of bugs such as twemproxy failing to parse certain responses. Bug fixes were merged, and will be part of an upcoming 0.5.0 release, which is still being prepared. See the changelog for details

- Redis errors without a space after the error type were incorrectly parsed
- Nested multibulk redis replies (arrays of arrays) were incorrectly parsed and clients would see twemproxy hanging.
