### ISSUE TITLE
Support for Redis 4.x?

### ISSUE THREAD

**Issue by ashu210890** [twitter/twemproxy#562]
I see that the last release was 3 years ago? Is this project still in active development? Can we use this with our Redis 4.x setup?

**Comment by xginn8** [comment]
Running the test suite against Redis 4.0.10 works for me (some memcached failures, but I assume they're unrelated), but ymmv since this project is nominally abandoned.2

**Comment by charsyam** [comment]
But it doesn't support new commands

**Comment by TysonAndre** [comment]
https://github.com/twitter/twemproxy/pull/599 adds support for some of the newer redis commands - it hasn't been manually tested yet, though

Older commands that are documented in https://github.com/twitter/twemproxy/blob/master/notes/redis.md#redis-command-support should work in twitter's currently available releases as long as they don't use new arguments (e.g. twitter/twemproxy only supports `EXIST` if there's one key right now)

**Comment by TysonAndre** [comment]
#599 was merged and should be in a 0.5.0 release
