### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by oogali** [twitter/twemproxy#564]
Is it possible to cut a new release?

### Expected behavior

After a significant amount of changes and or a significant amount of time (both to be decided on by project maintainers), a new release should be cut on Github.

### Actual behavior

There's been 53 commits to master since the last release: 0.4.1 (June 23, 2015). The most interesting of these being bug fixes that I'd imagine most people running this in production would like to adopt.

### Steps to reproduce the behavior

(not really applicable?)

**Comment by h0tw1r3** [comment]
project is dead.
twmemcache development continued as part of [pelikan](https://github.com/twitter/pelikan)
