### ISSUE TITLE
loga is asynchronous ?

### ISSUE THREAD

**Issue by tsunamitom** [twitter/twemproxy#575]
One line summary of the issue here.
i want write  key log ,loga is asynchronous ?  where is  nc_write
### Expected behavior

As concisely as possible, describe the expected behavior.

### Actual behavior

As concisely as possible, describe the observed behavior.

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

**Comment by TysonAndre** [comment]
1. logging is synchronous to a log file or stderr
2. nc_write is a `#define` C macro

```
src/nc_util.h
145:#define nc_write(_d, _b, _n)    \
148:#define nc_writev(_d, _b, _n)   \
```
