### ISSUE TITLE
2nd function call argument 'buf' is a pointer to uninitialized value

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [twitter/twemproxy#576]
2nd function call argument 'buf' is a pointer to uninitialized value

https://github.com/twitter/twemproxy/blob/c5c725d2b45715e378909ebc909b0492591c4715/src/nc_log.c#L257

'buf' initialized in line 209 
if in line 223, the condition is false ,'buf' is a uninitialized value.

**Comment by TysonAndre** [comment]
`len = 0` means buf being initialized won't matter - this is inactionable
