### ISSUE TITLE
Access to field 'start' result in a dereference of a null pointer

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [twitter/twemproxy#577]
Access to field 'start' result in a dereference of a null pointer (loaded from variable 'rsp_buffer')
https://github.com/twitter/twemproxy/blob/c5c725d2b45715e378909ebc909b0492591c4715/src/proto/nc_redis.c#L2943

in line 2940, Null pointer value stored to 'rsp_buffer'

**Comment by TysonAndre** [comment]
This seems like a false positive from an automated analysis tool

It doesn't seem to happen for various edge cases such as immediate rejection, invalid redis responses, or a server that doesn't send a response.
