### ISSUE TITLE
Does twemproxy works on network layer 4 ?

### ISSUE THREAD

**Issue by debjitk** [twitter/twemproxy#579]
Does **twemproxy** works on network **layer 4** ? For example **haproxy** which can work on layer 4 and layer 7 as well ?

**Comment by xishian** [comment]
NO, It works on layer 7, because it has to handle the application layer data(redis protocol).

**Comment by TysonAndre** [comment]
https://www.haproxy.com/blog/layer-4-and-layer-7-proxy-mode/ yes, twemproxy is layer 7 (similar to haproxy's http mode), since it parses and rebuilds all redis/memcache requests/responses in order to forward requests from multiple clients to multiple backend servers (and forward responses)
