### ISSUE TITLE
Single server configuration

### ISSUE THREAD

**Issue by enricopesce** [twitter/twemproxy#581]
I want to use Twemproxy to optimize the connections to one single Redis server, I can't fix or optimize the application code.

Is what the correct configuration about the hash and distribution algorithms with a single remote server?

An example of my configuration:

server:
  listen: 0.0.0.0:22223
  redis: true
  preconnect: true
  timeout: 5000
  redis_db: 0
  server_retry_timeout: 3000
  auto_eject_hosts: false
  distribution: ??????
  hash: ??????
  servers:
    - myserver:6379:1

**Comment by mcb0006** [comment]
> I want to use Twemproxy to optimize the connections to one single Redis server, I can't fix or optimize the application code.
> 
> 
> 
> Is what the correct configuration about the hash and distribution algorithms with a single remote server?
> 
> 
> 
> An example of my configuration:
> 
> 
> 
> server:
> 
>   listen: 0.0.0.0:22223
> 
>   redis: true
> 
>   preconnect: true
> 
>   timeout: 5000
> 
>   redis_db: 0
> 
>   server_retry_timeout: 3000
> 
>   auto_eject_hosts: false
> 
>   distribution: ??????
> 
>   hash: ??????
> 
>   servers:
> 
>     - owner.media:6379:1
> 
>

**Comment by mcb0006** [comment]
[@mboocannon]()

**Comment by TysonAndre** [comment]
This could safely be optimized inside twemproxy itself - you don't need to compute a hash or choose a server in a distribution if it's a choice of a single server. The result index is always 0.

```patch
@@ -890,10 +890,16 @@ uint32_t
 server_pool_idx(struct server_pool *pool, uint8_t *key, uint32_t keylen)
 {
     uint32_t hash, idx;
+    uint32_t nservers = array_n(&pool->server);
 
-    ASSERT(array_n(&pool->server) != 0);
+    ASSERT(nservers != 0);
     ASSERT(key != NULL);
 
+    if (nservers == 1) {
+        /* Optimization: Skip dispatching for pools with only one server */
+        return 0;
+    }
+
```

**Comment by TysonAndre** [comment]
Avoiding computing the hash and distribution for single server pools was done in https://github.com/twitter/twemproxy/commit/60252e1b971d8255e9e19e58c4548ba8b44e0c94 for 0.5.0
