### ISSUE TITLE
Ubuntu PPA error

### ISSUE THREAD

**Issue by durzo** [twitter/twemproxy#588]
When adding the Ubuntu PPA from the README, I get the following error:
```
E: The repository 'http://ppa.launchpad.net/twemproxy/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by abdidarmawan007** [comment]
i try install in ubuntu 20.04

sudo apt install nutcraker
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nutcraker

**Comment by abdidarmawan007** [comment]
Err:7 http://ppa.launchpad.net/twemproxy/stable/ubuntu focal Release     
  404  Not Found [IP: 91.189.95.83 80]


Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/twemproxy/stable/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
