### ISSUE TITLE
twemproxy does not startup if it cannot resolve hostnames

### ISSUE THREAD

**Issue by manjuraj** [twitter/twemproxy#64]
twemproxy does not startup if it cannot resolve hostnames. This might occur is you use name instead of IP address in your config file and twemproxy fails to resolve these names.

The fix for this to not lazily resolve hostnames rather than resolving them on start-up. If a name doesn't resolve on run-time then it is not included in the hash ring (cluster)

**Comment by scripthead** [comment]
There's another issue to where there's a limit to hostname length which presents a problem. In my environment hostnames are quite long, e.g. project-staging.fl8zqq.cfg.use1.cache.amazonaws.com which results in them getting cut off.

[Tue May  5 18:39:33 2015] nc.c:168 nutcracker-0.1.16 started on pid 20063
[Tue May  5 18:39:33 2015] nc.c:172 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one
[Tue May  5 18:39:33 2015] nc_util.c:481 address resolution of node 'project-staging.fl8zqq.cfg.use1.cache.amazon' service '11211' failed: Name or service not known
[Tue May  5 18:39:33 2015] nc_conf.c:482 conf: directive "servers" has an invalid value
[Tue May  5 18:39:33 2015] nc.c:178 done, rabbit done

**Comment by manjuraj** [comment]
fixed with this change: https://github.com/twitter/twemproxy/issues/355#issuecomment-113575050
duplicate of issue: https://github.com/twitter/twemproxy/issues/355
