### ISSUE TITLE
Cross Region Replication Support

### ISSUE THREAD

**Issue by NirmalP29** [twitter/twemproxy#663]
Is cross region uni directional replication supported in redis via twemproxy?

Scenario - 
Suppose there are two clusters A & B in region R1 & R2 respectively. All the write requests will go to cluster A in region R1 which will be replicated to cluster B in region R2 and all the read requests will go to nearest region. 

Feature - 
Is it possible to set up a server in twemproxy which will write to two clusters in one call (one IP+Port).
And it will have option to wait for successful write request in all the cluster, or a single cluster or quorum of clusters.

**Comment by TysonAndre** [comment]
> Is cross region uni directional replication supported in redis via twemproxy?

No, it isn't part of the current features. mcrouter (if you can set up prefixes for requests in your application) may help.

Memcached has a `noreply` option you can configure in libmemcached that may be useful if you want to manually do asynchronous writes in your application - mixing in noreply with the occasional synchronous command would help detect disconnected connections.

Doing very simple things in c such as replicating sets/deletes/adds is possible, but not implemented, and may be inconvenient

> Is it possible to set up a server in twemproxy which will write to two clusters in one call (one IP+Port).


> And it will have option to wait for successful write request in all the cluster, or a single cluster or quorum ok clusters.

https://github.com/memcached/memcached/wiki/Proxy is a relatively new development that may be useful, though it may be months before there's a stable release, not familiar with the timeline for 1.7.0 and their plans may change.

> The proxy is ready for *preview* and *early testing,* we are still working on "productionizing" the proxy.

The lua scripting it has may let you do quorum or customizable cluster logic in principle https://github.com/memcached/memcached/ (e.g. waiting for the first `count` successful responses)
