### ISSUE TITLE
add HRANDFIELD 

### ISSUE THREAD

**Issue by artarik** [twitter/twemproxy#669]
Hello
whether there are plans to add this command HRANDFIELD?
https://redis.io/commands/hrandfield/

**Comment by yuerugou54** [comment]
马晓栋已经收到您的来件，谢谢!

**Comment by dev-lemontree** [comment]
@artarik I think it is already supported in master branch

**Comment by artarik** [comment]
@dev-lemontree  I did not see the parameter in [list](https://github.com/twitter/twemproxy/blob/master/notes/redis.md), which is why the question arose
Thanks

**Comment by dev-lemontree** [comment]
Please see the code. 
https://github.com/twitter/twemproxy/blob/master/src/proto/nc_redis.c#L228
